<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Carrera extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Carrera_model');
    } 

    /*
     * Listing of carreras
     */
    function index()
    {
        $data['carreras'] = $this->Carrera_model->get_all_carreras();

        $this->load->view('carrera/index',$data);
    }

    /*
     * Adding a new carrera
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ESC_CODIGO' => $this->input->post('ESC_CODIGO'),
				'CARR_DESCRIPCION' => $this->input->post('CARR_DESCRIPCION'),
            );
            
            $carrera_id = $this->Carrera_model->add_carrera($params);
            redirect('carrera/index');
        }
        else
        {

			$this->load->model('Escuela_model');
			$data['all_escuelas'] = $this->Escuela_model->get_all_escuelas();
                
            $this->load->view('carrera/add',$data);
        }
    }  

    /*
     * Editing a carrera
     */
    function edit($CARR_CODIGO)
    {   
        // check if the carrera exists before trying to edit it
        $carrera = $this->Carrera_model->get_carrera($CARR_CODIGO);
        
        if(isset($carrera['CARR_CODIGO']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ESC_CODIGO' => $this->input->post('ESC_CODIGO'),
					'CARR_DESCRIPCION' => $this->input->post('CARR_DESCRIPCION'),
                );

                $this->Carrera_model->update_carrera($CARR_CODIGO,$params);            
                redirect('carrera/index');
            }
            else
            {   
                $data['carrera'] = $this->Carrera_model->get_carrera($CARR_CODIGO);
    
				$this->load->model('Escuela_model');
				$data['all_escuelas'] = $this->Escuela_model->get_all_escuelas();

                $this->load->view('carrera/edit',$data);
            }
        }
        else
            show_error('The carrera you are trying to edit does not exist.');
    } 

    /*
     * Deleting carrera
     */
    function remove($CARR_CODIGO)
    {
        $carrera = $this->Carrera_model->get_carrera($CARR_CODIGO);

        // check if the carrera exists before trying to delete it
        if(isset($carrera['CARR_CODIGO']))
        {
            $this->Carrera_model->delete_carrera($CARR_CODIGO);
            redirect('carrera/index');
        }
        else
            show_error('The carrera you are trying to delete does not exist.');
    }
    
}
