<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Dicta extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dicta_model');
    } 

    /*
     * Listing of dicta
     */
    function index()
    {
        $data['dicta'] = $this->Dicta_model->get_all_dicta();

        $this->load->view('dicta/index',$data);
    }

    /*
     * Adding a new dicta
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $dicta_id = $this->Dicta_model->add_dicta($params);
            redirect('dicta/index');
        }
        else
        {
            $this->load->view('dicta/add');
        }
    }  

    /*
     * Editing a dicta
     */
    function edit($prof_codigo)
    {   
        // check if the dicta exists before trying to edit it
        $dicta = $this->Dicta_model->get_dicta($prof_codigo);
        
        if(isset($dicta['prof_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Dicta_model->update_dicta($prof_codigo,$params);            
                redirect('dicta/index');
            }
            else
            {   
                $data['dicta'] = $this->Dicta_model->get_dicta($prof_codigo);
    
                $this->load->view('dicta/edit',$data);
            }
        }
        else
            show_error('The dicta you are trying to edit does not exist.');
    } 

    /*
     * Deleting dicta
     */
    function remove($prof_codigo)
    {
        $dicta = $this->Dicta_model->get_dicta($prof_codigo);

        // check if the dicta exists before trying to delete it
        if(isset($dicta['prof_codigo']))
        {
            $this->Dicta_model->delete_dicta($prof_codigo);
            redirect('dicta/index');
        }
        else
            show_error('The dicta you are trying to delete does not exist.');
    }
    
}
