<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Escuelas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Escuelas_model');
    } 

    /*
     * Listing of escuelas
     */
    function index()
    {
        $data['escuelas'] = $this->Escuelas_model->get_all_escuelas();

        $this->load->view('escuelas/index',$data);
    }

    /*
     * Adding a new escuelas
     */
    function add()
    {
        $this->load->library('form_validation');
        //Agregado
        $this->db->select_max('esc_codigo');
        $result= $this->db->get('escuelas')->row_array();
        //echo $result['per_codigo'];
        //
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                //agregado
                'esc_codigo' =>$result['esc_codigo']+1,
                //
				'facu_codigo' => $this->input->post('facu_codigo'),
				'esc_descripcion' => $this->input->post('esc_descripcion'),
            );
            
            $escuelas_id = $this->Escuelas_model->add_escuelas($params);
            redirect('escuelas/index');
        }
        else
        {
            $this->load->view('escuelas/add');
        }
    }  

    /*
     * Editing a escuelas
     */
    function edit($esc_codigo)
    {
        $this->load->library('form_validation');
        // check if the escuelas exists before trying to edit it
        $escuelas = $this->Escuelas_model->get_escuelas($esc_codigo);
        
        if(isset($escuelas['esc_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'facu_codigo' => $this->input->post('facu_codigo'),
					'esc_descripcion' => $this->input->post('esc_descripcion'),
                );

                $this->Escuelas_model->update_escuelas($esc_codigo,$params);            
                redirect('escuelas/index');
            }
            else
            {   
                $data['escuelas'] = $this->Escuelas_model->get_escuelas($esc_codigo);
    
                $this->load->view('escuelas/edit',$data);
            }
        }
        else
            show_error('The escuelas you are trying to edit does not exist.');
    } 

    /*
     * Deleting escuelas
     */
    function remove($esc_codigo)
    {
        $escuelas = $this->Escuelas_model->get_escuelas($esc_codigo);

        // check if the escuelas exists before trying to delete it
        if(isset($escuelas['esc_codigo']))
        {
            $this->Escuelas_model->delete_escuelas($esc_codigo);
            redirect('escuelas/index');
        }
        else
            show_error('The escuelas you are trying to delete does not exist.');
    }
    
}
