<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Examen_complexivo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Examen_complexivo_model');
    } 

    /*
     * Listing of examen_complexivo
     */
    function index()
    {
        $data['examen_complexivo'] = $this->Examen_complexivo_model->get_all_examen_complexivo();

        $this->load->helper('form');
        $this->load->helper(array('form'));
        $this->load->view('templates/header');
        $this->load->view('examen_complexivo/index',$data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new examen_complexivo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('per_codigo','Per Codigo','integer');
		$this->form_validation->set_rules('exa_fechainicio','Exa Fechainicio','required');
		$this->form_validation->set_rules('exa_estado','Exa Estado','required');
		
		if($this->form_validation->run())     
        {
            $this->db->select_max('exa_codigo');
            $result= $this->db->get('examen_complexivo')->row_array();
            $params = array(
                'exa_codigo' =>$result['exa_codigo']+1,
				'per_codigo' => $this->input->post('per_codigo'),
				'exa_fechainicio' => $this->input->post('exa_fechainicio'),
				'exa_estado' => $this->input->post('exa_estado'),
            );
            
            $examen_complexivo_id = $this->Examen_complexivo_model->add_examen_complexivo($params);
            redirect('examen_complexivo/index');
        }
        else
        {

			$this->load->model('Estudiante_model');
			$data['all_estudiante'] = $this->Estudiante_model->get_all_estudiantes();

            $this->load->view('templates/header');
			$this->load->view('examen_complexivo/add',$data);
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a examen_complexivo
     */
    function edit($exa_codigo)
    {   
        // check if the examen_complexivo exists before trying to edit it
        $examen_complexivo = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);
        
        if(isset($examen_complexivo['exa_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('per_codigo','Per Codigo','integer');
			$this->form_validation->set_rules('exa_fechainicio','Exa Fechainicio','required');
			$this->form_validation->set_rules('exa_estado','Exa Estado','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'per_codigo' => $this->input->post('per_codigo'),
					'exa_fechainicio' => $this->input->post('exa_fechainicio'),
					'exa_estado' => $this->input->post('exa_estado'),
                );

                $this->Examen_complexivo_model->update_examen_complexivo($exa_codigo,$params);            
                redirect('examen_complexivo/index');
            }
            else
            {   
                $data['examen_complexivo'] = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);
    
				$this->load->model('Estudiante_model');
				$data['all_estudiante'] = $this->Estudiante_model->get_all_estudiantes();

				$this->load->view('templates/header');
				$this->load->view('examen_complexivo/edit',$data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The examen_complexivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting examen_complexivo
     */
    function remove($exa_codigo)
    {
        $examen_complexivo = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);

        // check if the examen_complexivo exists before trying to delete it
        if(isset($examen_complexivo['exa_codigo']))
        {
            $this->Examen_complexivo_model->delete_examen_complexivo($exa_codigo);
            redirect('examen_complexivo/index');
        }
        else
            show_error('The examen_complexivo you are trying to delete does not exist.');
    }
    
}
