<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Examen_complexivo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Examen_complexivo_model');
    } 

    /*
     * Listing of examenes_complexivo
     */
    function index()
    {
        $data['examenes_complexivo'] = $this->Examen_complexivo_model->get_all_examenes_complexivo();

        $this->load->view('examen_complexivo/index',$data);
    }

    /*
     * Adding a new examen_complexivo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('est_codigo','Est Codigo','integer');
		$this->form_validation->set_rules('exa_fechainicio','Exa Fechainicio','required');
		$this->form_validation->set_rules('exa_estado','Exa Estado','required');
		$this->form_validation->set_rules('exa_horas_docencia','Exa Horas Docencia','integer');
		$this->form_validation->set_rules('exa_horas_autonomas','Exa Horas Autonomas','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'est_codigo' => $this->input->post('est_codigo'),
				'exa_fechainicio' => $this->input->post('exa_fechainicio'),
				'exa_estado' => $this->input->post('exa_estado'),
				'exa_horas_docencia' => $this->input->post('exa_horas_docencia'),
				'exa_horas_autonomas' => $this->input->post('exa_horas_autonomas'),
            );
            
            $examen_complexivo_id = $this->Examen_complexivo_model->add_examen_complexivo($params);
            redirect('examen_complexivo/index');
        }
        else
        {

			$this->load->model('Estudiante_model');
			$data['all_estudiantes'] = $this->Estudiante_model->get_all_estudiantes();
                
            $this->load->view('examen_complexivo/add',$data);
        }
    }  

    /*
     * Editing a examen_complexivo
     */
    function edit($exa_codigo)
    {   
        // check if the examen_complexivo exists before trying to edit it
        $examen_complexivo = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);
        
        if(isset($examen_complexivo['exa_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('est_codigo','Est Codigo','integer');
			$this->form_validation->set_rules('exa_fechainicio','Exa Fechainicio','required');
			$this->form_validation->set_rules('exa_estado','Exa Estado','required');
			$this->form_validation->set_rules('exa_horas_docencia','Exa Horas Docencia','integer');
			$this->form_validation->set_rules('exa_horas_autonomas','Exa Horas Autonomas','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'est_codigo' => $this->input->post('est_codigo'),
					'exa_fechainicio' => $this->input->post('exa_fechainicio'),
					'exa_estado' => $this->input->post('exa_estado'),
					'exa_horas_docencia' => $this->input->post('exa_horas_docencia'),
					'exa_horas_autonomas' => $this->input->post('exa_horas_autonomas'),
                );

                $this->Examen_complexivo_model->update_examen_complexivo($exa_codigo,$params);            
                redirect('examen_complexivo/index');
            }
            else
            {   
                $data['examen_complexivo'] = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);
    
				$this->load->model('Estudiante_model');
				$data['all_estudiantes'] = $this->Estudiante_model->get_all_estudiantes();

                $this->load->view('examen_complexivo/edit',$data);
            }
        }
        else
            show_error('The examen_complexivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting examen_complexivo
     */
    function remove($exa_codigo)
    {
        $examen_complexivo = $this->Examen_complexivo_model->get_examen_complexivo($exa_codigo);

        // check if the examen_complexivo exists before trying to delete it
        if(isset($examen_complexivo['exa_codigo']))
        {
            $this->Examen_complexivo_model->delete_examen_complexivo($exa_codigo);
            redirect('examen_complexivo/index');
        }
        else
            show_error('The examen_complexivo you are trying to delete does not exist.');
    }
    
}
