<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Facultades extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Facultades_model');
    } 

    /*
     * Listing of facultades
     */
    function index()
    {
        $data['facultades'] = $this->Facultades_model->get_all_facultades();

        $this->load->view('facultades/index',$data);
    }

    /*
     * Adding a new facultades
     */
    function add()
    {
        $this->load->library('form_validation');

        //Agregado
        $this->db->select_max('facu_codigo');
        $result= $this->db->get('facultades')->row_array();
        //echo $result['facu_codigo'];
        //

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                //agregado
                'facu_codigo' =>$result['facu_codigo']+1,
                //
				'facu_descripcion' => $this->input->post('facu_descripcion'),
            );
            
            $facultades_id = $this->Facultades_model->add_facultades($params);
            redirect('facultades/index');
        }
        else
        {
            $this->load->view('facultades/add');
        }
    }  

    /*
     * Editing a facultades
     */
    function edit($facu_codigo)
    {
        $this->load->library('form_validation');
        // check if the facultades exists before trying to edit it
        $facultades = $this->Facultades_model->get_facultades($facu_codigo);
        
        if(isset($facultades['facu_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'facu_descripcion' => $this->input->post('facu_descripcion'),
                );

                $this->Facultades_model->update_facultades($facu_codigo,$params);            
                redirect('facultades/index');
            }
            else
            {   
                $data['facultades'] = $this->Facultades_model->get_facultades($facu_codigo);
    
                $this->load->view('facultades/edit',$data);
            }
        }
        else
            show_error('The facultades you are trying to edit does not exist.');
    } 

    /*
     * Deleting facultades
     */
    function remove($facu_codigo)
    {
        $facultades = $this->Facultades_model->get_facultades($facu_codigo);

        // check if the facultades exists before trying to delete it
        if(isset($facultades['facu_codigo']))
        {
            $this->Facultades_model->delete_facultades($facu_codigo);
            redirect('facultades/index');
        }
        else
            show_error('The facultades you are trying to delete does not exist.');
    }
    
}
