<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Intento extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Intento_model');
    } 

    /*
     * Listing of intentos
     */
    function index()
    {
        $data['intentos'] = $this->Intento_model->get_all_intentos();

        $this->load->view('intentos/index',$data);
    }

    /*
     * Adding a new intento
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('exa_codigo','Exa Codigo','integer');
		$this->form_validation->set_rules('int_fechaint','Int Fechaint','required');
		
		if($this->form_validation->run())     
        {
            $this->db->select_max('int_codigo');
            $result= $this->db->get('intentos')->row_array();
            $params = array(
                'int_codigo' =>$result['int_codigo']+1,
				'exa_codigo' => $this->input->post('exa_codigo'),
				'int_fechaint' => $this->input->post('int_fechaint'),
            );
            
            $intento_id = $this->Intento_model->add_intento($params);
            redirect('intento/index');
        }
        else
        {

			$this->load->model('Examen_complexivo_model');
			$data['all_examen_complexivo'] = $this->Examen_complexivo_model->get_all_examen_complexivo();
                
            $this->load->view('intentos/add',$data);
        }
    }  

    /*
     * Editing a intento
     */
    function edit($int_codigo)
    {   
        // check if the intento exists before trying to edit it
        $intento = $this->Intento_model->get_intento($int_codigo);
        
        if(isset($intento['int_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('exa_codigo','Exa Codigo','integer');
			$this->form_validation->set_rules('int_fechaint','Int Fechaint','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'exa_codigo' => $this->input->post('exa_codigo'),
					'int_fechaint' => $this->input->post('int_fechaint'),
                );

                $this->Intento_model->update_intento($int_codigo,$params);            
                redirect('intento/index');
            }
            else
            {   
                $data['intento'] = $this->Intento_model->get_intento($int_codigo);
    
				$this->load->model('Examen_complexivo_model');
				$data['all_examen_complexivo'] = $this->Examen_complexivo_model->get_all_examen_complexivo();

                $this->load->view('intentos/edit',$data);
            }
        }
        else
            show_error('The intento you are trying to edit does not exist.');
    } 

    /*
     * Deleting intento
     */
    function remove($int_codigo)
    {
        $intento = $this->Intento_model->get_intento($int_codigo);

        // check if the intento exists before trying to delete it
        if(isset($intento['int_codigo']))
        {
            $this->Intento_model->delete_intento($int_codigo);
            redirect('intento/index');
        }
        else
            show_error('The intento you are trying to delete does not exist.');
    }
    
}
