<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Materia extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Materia_model');
    } 

    /*
     * Listing of materias
     */
    function index()
    {
        $data['materias'] = $this->Materia_model->get_all_materias();

        $this->load->view('materia/index',$data);
    }

    /*
     * Adding a new materia
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('mat_nombre','Mat Nombre','required|max_length[100]');
		$this->form_validation->set_rules('mat_nivel','Mat Nivel','required|integer');
		
		if($this->form_validation->run())     
        {
            //Agregado
            $this->db->select_max('mat_codigo');
            $result= $this->db->get('materias')->row_array();
            //echo $result['per_codigo'];
            //
            $params = array(
                'mat_codigo' =>$result['mat_codigo']+1,
				'mat_nombre' => $this->input->post('mat_nombre'),
				'mat_nivel' => $this->input->post('mat_nivel'),
            );
            
            $materia_id = $this->Materia_model->add_materia($params);
            redirect('materia/index');
        }
        else
        {
            $this->load->view('materia/add');
        }
    }  

    /*
     * Editing a materia
     */
    function edit($mat_codigo)
    {   
        // check if the materia exists before trying to edit it
        $materia = $this->Materia_model->get_materia($mat_codigo);
        
        if(isset($materia['mat_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('mat_nombre','Mat Nombre','required|max_length[100]');
			$this->form_validation->set_rules('mat_nivel','Mat Nivel','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'mat_nombre' => $this->input->post('mat_nombre'),
					'mat_nivel' => $this->input->post('mat_nivel'),
                );

                $this->Materia_model->update_materia($mat_codigo,$params);            
                redirect('materia/index');
            }
            else
            {   
                $data['materia'] = $this->Materia_model->get_materia($mat_codigo);
    
                $this->load->view('materia/edit',$data);
            }
        }
        else
            show_error('The materia you are trying to edit does not exist.');
    } 

    /*
     * Deleting materia
     */
    function remove($mat_codigo)
    {
        $materia = $this->Materia_model->get_materia($mat_codigo);

        // check if the materia exists before trying to delete it
        if(isset($materia['mat_codigo']))
        {
            $this->Materia_model->delete_materia($mat_codigo);
            redirect('materia/index');
        }
        else
            show_error('The materia you are trying to delete does not exist.');
    }
    
}
