<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Materia_x_plan_de_estudio extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Materia_x_plan_de_estudio_model');
    } 

    /*
     * Listing of materia_x_plan_de_estudio
     */
    function index()
    {
        $data['materia_x_plan_de_estudio'] = $this->Materia_x_plan_de_estudio_model->get_all_materia_x_plan_de_estudio();

        $this->load->view('materia_x_plan_de_estudio/index',$data);
    }

    /*
     * Adding a new materia_x_plan_de_estudio
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('plan_codigo','Plan de Estudio','required');
        $this->form_validation->set_rules('mat_codigo','Materia','required');
        $this->form_validation->set_rules('pac_codigo','Periodo académico','required');

        if($this->form_validation->run())
        {

            $params = array(
                'plan_codigo'=>$this->input->post('plan_codigo'),
                'mat_codigo'=>$this->input->post('mat_codigo'),
                'pac_codigo'=>$this->input->post('pac_codigo'),
            );
            
            $materia_x_plan_de_estudio_id = $this->Materia_x_plan_de_estudio_model->add_materia_x_plan_de_estudio($params);
            redirect('materia_x_plan_de_estudio/index');
        }
        else
        {

            $this->load->model('Plan_de_estudio_model');
            $data['all_planes'] = $this->Plan_de_estudio_model->get_all_planes_de_estudio();
            $this->load->model('Materia_model');
            $data['all_materias'] = $this->Materia_model->get_all_materias();
            $this->load->model('Periodos_academicos_model');
            $data['all_pac'] = $this->Periodos_academicos_model->get_all_periodos_academicos();

            $this->load->view('materia_x_plan_de_estudio/add',$data);
        }
    }  

    /*
     * Editing a materia_x_plan_de_estudio
     */
    function edit($plan_codigo,$mat_codigo,$pac_codigo)
    {   
        // check if the materia_x_plan_de_estudio exists before trying to edit it
        $materia_x_plan_de_estudio = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo);
        
        if(isset($materia_x_plan_de_estudio['plan_codigo'])&&isset($materia_x_plan_de_estudio['mat_codigo'])&&isset($materia_x_plan_de_estudio['pac_codigo']))
        {
            $this->load->library('form_validation');

            if($this->form_validation->run())
            {   
                $params = array(
                );

                $this->Materia_x_plan_de_estudio_model->update_materia_x_plan_de_estudio($plan_codigo,$params);            
                redirect('materia_x_plan_de_estudio/index');
            }
            else
            {   
                $data['materia_x_plan_de_estudio'] = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo);
    
                $this->load->view('materia_x_plan_de_estudio/edit',$data);
            }
        }
        else
            show_error('The materia_x_plan_de_estudio you are trying to edit does not exist.');
    } 

    /*
     * Deleting materia_x_plan_de_estudio
     */
    function remove($plan_codigo,$mat_codigo,$pac_codigo)
    {
        $materia_x_plan_de_estudio = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo);

        // check if the materia_x_plan_de_estudio exists before trying to delete it
        if(isset($materia_x_plan_de_estudio['plan_codigo']))
        {
            $this->Materia_x_plan_de_estudio_model->delete_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo);
            redirect('materia_x_plan_de_estudio/index');
        }
        else
            show_error('The materia_x_plan_de_estudio you are trying to delete does not exist.');
    }
    
}
