<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Materia_x_plan_de_estudio extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Materia_x_plan_de_estudio_model');
    } 

    /*
     * Listing of materia_x_plan_de_estudio
     */
    function index()
    {
        $data['materia_x_plan_de_estudio'] = $this->Materia_x_plan_de_estudio_model->get_all_materia_x_plan_de_estudio();

        $this->load->view('materia_x_plan_de_estudio/index',$data);
    }

    /*
     * Adding a new materia_x_plan_de_estudio
     */
    function add()
    {
        $this->load->library('form_validation');

        if(isset($_POST) && count($_POST) > 0)
        {   
            $params = array(
            );
            
            $materia_x_plan_de_estudio_id = $this->Materia_x_plan_de_estudio_model->add_materia_x_plan_de_estudio($params);
            redirect('materia_x_plan_de_estudio/index');
        }
        else
        {
            $this->load->view('materia_x_plan_de_estudio/add');
        }
    }  

    /*
     * Editing a materia_x_plan_de_estudio
     */
    function edit($plan_codigo)
    {   
        // check if the materia_x_plan_de_estudio exists before trying to edit it
        $materia_x_plan_de_estudio = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo);
        
        if(isset($materia_x_plan_de_estudio['plan_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Materia_x_plan_de_estudio_model->update_materia_x_plan_de_estudio($plan_codigo,$params);            
                redirect('materia_x_plan_de_estudio/index');
            }
            else
            {   
                $data['materia_x_plan_de_estudio'] = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo);
    
                $this->load->view('materia_x_plan_de_estudio/edit',$data);
            }
        }
        else
            show_error('The materia_x_plan_de_estudio you are trying to edit does not exist.');
    } 

    /*
     * Deleting materia_x_plan_de_estudio
     */
    function remove($plan_codigo)
    {
        $materia_x_plan_de_estudio = $this->Materia_x_plan_de_estudio_model->get_materia_x_plan_de_estudio($plan_codigo);

        // check if the materia_x_plan_de_estudio exists before trying to delete it
        if(isset($materia_x_plan_de_estudio['plan_codigo']))
        {
            $this->Materia_x_plan_de_estudio_model->delete_materia_x_plan_de_estudio($plan_codigo);
            redirect('materia_x_plan_de_estudio/index');
        }
        else
            show_error('The materia_x_plan_de_estudio you are trying to delete does not exist.');
    }
    
}
