<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Modulo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Modulo_model');
    } 

    /*
     * Listing of modulos
     */
    function index()
    {
        $data['modulos'] = $this->Modulo_model->get_all_modulos();

        $this->load->view('modulos/index',$data);
    }

    /*
     * Adding a new modulo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('mod_descripcion','Mod Descripcion','required|max_length[100]');
		
		if($this->form_validation->run())     
        {
            $this->db->select_max('mod_codigo');
            $result= $this->db->get('modulo')->row_array();
            $params = array(
                'mod_codigo' =>$result['mod_codigo']+1,
				'mod_descripcion' => $this->input->post('mod_descripcion'),
            );
            
            $modulo_id = $this->Modulo_model->add_modulo($params);
            redirect('modulo/index');
        }
        else
        {
            $this->load->view('modulos/add');
        }
    }  

    /*
     * Editing a modulo
     */
    function edit($mod_codigo)
    {   
        // check if the modulo exists before trying to edit it
        $modulo = $this->Modulo_model->get_modulo($mod_codigo);
        
        if(isset($modulo['mod_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('mod_descripcion','Mod Descripcion','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'mod_descripcion' => $this->input->post('mod_descripcion'),
                );

                $this->Modulo_model->update_modulo($mod_codigo,$params);            
                redirect('modulo/index');
            }
            else
            {   
                $data['modulo'] = $this->Modulo_model->get_modulo($mod_codigo);
    
                $this->load->view('modulos/edit',$data);
            }
        }
        else
            show_error('The modulo you are trying to edit does not exist.');
    } 

    /*
     * Deleting modulo
     */
    function remove($mod_codigo)
    {
        $modulo = $this->Modulo_model->get_modulo($mod_codigo);

        // check if the modulo exists before trying to delete it
        if(isset($modulo['mod_codigo']))
        {
            $this->Modulo_model->delete_modulo($mod_codigo);
            redirect('modulo/index');
        }
        else
            show_error('The modulo you are trying to delete does not exist.');
    }
    
}
