<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Periodos_academicos extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Periodos_academicos_model');
    } 

    /*
     * Listing of periodos_academicos
     */
    private $limit = 5;
    function index()
    {
        $data['periodos_academicos'] = $this->Periodos_academicos_model->get_all_periodos_academicos();

        /*Empiezo de paginacion*/
        $total_rows = $this->Periodos_academicos_model->count();

        $this->load->library('pagination');
        $config['total_rows'] = $total_rows;
        $config['per_page'] = $this->limit;
        $config['uri_segment'] = 3;
        $config['base_url'] = base_url().'/periodos_academicos/index';

        //CSS
        $config['full_tag_open'] = '<ul class="tsc_pagination tsc_paginationA tsc_paginationA01">';
        $config['full_tag_close'] = '</ul>';
        $config['prev_link'] = '&lt;';
        $config['prev_tag_open'] = '<li>';
        $config['prev_tag_close'] = '</li>';
        $config['next_link'] = '&gt;';
        $config['next_tag_open'] = '<li>';
        $config['next_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="current"><a href="#">';
        $config['cur_tag_close'] = '</a></li>';
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';

        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';

        $config['first_link'] = '&lt;&lt;';
        $config['last_link'] = '&gt;&gt;';
        //Fin CSS
        $this->pagination->initialize($config);

        $page_links = $this->pagination->create_links();
        $data['links'] = explode('&nbsp;',$page_links );
        /*Fin de paginacion*/

        $this->load->helper('form');
        $this->load->helper(array('form'));
        $this->load->view('templates/header');
        $this->load->view('periodos_academicos/index', $data);
        $this->load->view('templates/footer');
    }


    /*
     * Adding a new periodos_academicos
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('pac_descripcion','Pac Descripcion','required|max_length[30]');
		$this->form_validation->set_rules('pac_fechainicio','Pac Fechainicio','required');
		$this->form_validation->set_rules('pac_fechafinal','Pac Fechafinal','required');
		$this->form_validation->set_rules('pac_perido','Pac Perido','integer');
		
		if($this->form_validation->run())     
        {
            $this->db->select_max('pac_codigo');
            $result= $this->db->get('periodos_academicos')->row_array();
            $params = array(
                'pac_codigo' =>$result['pac_codigo']+1,
				'pac_descripcion' => $this->input->post('pac_descripcion'),
				'pac_fechainicio' => $this->input->post('pac_fechainicio'),
				'pac_fechafinal' => $this->input->post('pac_fechafinal'),
				'pac_perido' => $this->input->post('pac_perido'),
            );
            
            $periodos_academicos_id = $this->Periodos_academicos_model->add_periodos_academicos($params);
            redirect('periodos_academicos/index');
        }
        else
        {
            $this->load->view('templates/header');
            $this->load->view('periodos_academicos/add');
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a periodos_academicos
     */
    function edit($pac_codigo)
    {   
        // check if the periodos_academicos exists before trying to edit it
        $periodos_academicos = $this->Periodos_academicos_model->get_periodos_academicos($pac_codigo);
        
        if(isset($periodos_academicos['pac_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('pac_descripcion','Pac Descripcion','required|max_length[30]');
			$this->form_validation->set_rules('pac_fechainicio','Pac Fechainicio','required');
			$this->form_validation->set_rules('pac_fechafinal','Pac Fechafinal','required');
			$this->form_validation->set_rules('pac_perido','Pac Perido','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'pac_descripcion' => $this->input->post('pac_descripcion'),
					'pac_fechainicio' => $this->input->post('pac_fechainicio'),
					'pac_fechafinal' => $this->input->post('pac_fechafinal'),
					'pac_perido' => $this->input->post('pac_perido'),
                );

                $this->Periodos_academicos_model->update_periodos_academicos($pac_codigo,$params);            
                redirect('periodos_academicos/index');
            }
            else
            {   
                $data['periodos_academicos'] = $this->Periodos_academicos_model->get_periodos_academicos($pac_codigo);

                $this->load->view('templates/header');
                $this->load->view('periodos_academicos/edit', $data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The periodos_academicos you are trying to edit does not exist.');
    } 

    /*
     * Deleting periodos_academicos
     */
    function remove($pac_codigo)
    {
        $periodos_academicos = $this->Periodos_academicos_model->get_periodos_academicos($pac_codigo);

        // check if the periodos_academicos exists before trying to delete it
        if(isset($periodos_academicos['pac_codigo']))
        {
            $this->Periodos_academicos_model->delete_periodos_academicos($pac_codigo);
            redirect('periodos_academicos/index');
        }
        else
            show_error('The periodos_academicos you are trying to delete does not exist.');
    }
    
}
