<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Permiso extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Permiso_model');
    } 

    /*
     * Listing of permisos
     */
    function index()
    {
        $data['permisos'] = $this->Permiso_model->get_all_permisos();

        $this->load->view('permiso/index',$data);
    }

    /*
     * Adding a new permiso
     */
    function add()
    {
        $this->load->library('form_validation');
        if(isset($_POST) && count($_POST) > 0)     
        {
            //Agregado
            $this->db->select_max('perm_codigo');
            $result= $this->db->get('permisos')->row_array();
            //
            $params = array(
                //agregado
                'perm_codigo' =>$result['perm_codigo']+1,
                //
				'perm_estado' => $this->input->post('perm_estado'),
				'perm_creat' => $this->input->post('perm_creat'),
				'perm_read' => $this->input->post('perm_read'),
				'perm_update' => $this->input->post('perm_update'),
				'perm_delete' => $this->input->post('perm_delete'),
            );
            
            $permiso_id = $this->Permiso_model->add_permiso($params);
            redirect('permiso/index');
        }
        else
        {
            $this->load->view('permiso/add');
        }
    }  

    /*
     * Editing a permiso
     */
    function edit($perm_codigo)
    {
        $this->load->library('form_validation');
        // check if the permiso exists before trying to edit it
        $permiso = $this->Permiso_model->get_permiso($perm_codigo);
        
        if(isset($permiso['perm_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'perm_estado' => $this->input->post('perm_estado'),
					'perm_creat' => $this->input->post('perm_creat'),
					'perm_read' => $this->input->post('perm_read'),
					'perm_update' => $this->input->post('perm_update'),
					'perm_delete' => $this->input->post('perm_delete'),
                );

                $this->Permiso_model->update_permiso($perm_codigo,$params);
                redirect('permiso/index');
            }
            else
            {   
                $data['permiso'] = $this->Permiso_model->get_permiso($perm_codigo);
    
                $this->load->view('permiso/edit',$data);
            }
        }
        else
            show_error('The permiso you are trying to edit does not exist.');
    } 

    /*
     * Deleting permiso
     */
    function remove($perm_codigo)
    {
        $permiso = $this->Permiso_model->get_permiso($perm_codigo);

        // check if the permiso exists before trying to delete it
        if(isset($permiso['perm_codigo']))
        {
            $this->Permiso_model->delete_permiso($perm_codigo);
            redirect('permiso/index');
        }
        else
            show_error('The permiso you are trying to delete does not exist.');
    }
    
}
