<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Permxrol extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Permxrol_model');
    } 

    /*
     * Listing of permxrol
     */
    function index()
    {
        $data['permxrol'] = $this->Permxrol_model->get_all_permxrol();

        $this->load->view('permxrol/index',$data);
    }

    /*
     * Adding a new permxrol
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $permxrol_id = $this->Permxrol_model->add_permxrol($params);
            redirect('permxrol/index');
        }
        else
        {
            $this->load->view('permxrol/add');
        }
    }  

    /*
     * Editing a permxrol
     */
    function edit($zpermcodigo)
    {   
        // check if the permxrol exists before trying to edit it
        $permxrol = $this->Permxrol_model->get_permxrol($zpermcodigo);
        
        if(isset($permxrol['zpermcodigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Permxrol_model->update_permxrol($zpermcodigo,$params);            
                redirect('permxrol/index');
            }
            else
            {   
                $data['permxrol'] = $this->Permxrol_model->get_permxrol($zpermcodigo);
    
                $this->load->view('permxrol/edit',$data);
            }
        }
        else
            show_error('The permxrol you are trying to edit does not exist.');
    } 

    /*
     * Deleting permxrol
     */
    function remove($zpermcodigo)
    {
        $permxrol = $this->Permxrol_model->get_permxrol($zpermcodigo);

        // check if the permxrol exists before trying to delete it
        if(isset($permxrol['zpermcodigo']))
        {
            $this->Permxrol_model->delete_permxrol($zpermcodigo);
            redirect('permxrol/index');
        }
        else
            show_error('The permxrol you are trying to delete does not exist.');
    }
    
}
