<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Permxrol extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Permxrol_model');
    } 

    /*
     * Listing of permxrol
     */
    private $limit = 5;
    function index()
    {
        $data['permxrol'] = $this->Permxrol_model->get_all_permxrol();

        /*Empiezo de paginacion*/
        $total_rows = $this->Permxrol_model->count();

        $this->load->library('pagination');
        $config['total_rows'] = $total_rows;
        $config['per_page'] = $this->limit;
        $config['uri_segment'] = 3;
        $config['base_url'] = base_url().'/permxrol/index';
        $this->pagination->initialize($config);

        $page_links = $this->pagination->create_links();
        $data['links'] = explode('&nbsp;',$page_links );
        /*Fin de paginacion*/

        $this->load->helper('form');
        $this->load->helper(array('form'));
        $this->load->view('templates/header');
        $this->load->view('permxrol/index', $data);
        $this->load->view('templates/footer');
    }

    /*
     * Adding a new permxrol
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $permxrol_id = $this->Permxrol_model->add_permxrol($params);
            redirect('permxrol/index');
        }
        else
        {
            $this->load->view('templates/header');
            $this->load->view('permxrol/add');
            $this->load->view('templates/footer');
        }
    }  

    /*
     * Editing a permxrol
     */
    function edit($perm_codigo)
    {   
        // check if the permxrol exists before trying to edit it
        $permxrol = $this->Permxrol_model->get_permxrol($perm_codigo);
        
        if(isset($permxrol['perm_codigo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Permxrol_model->update_permxrol($perm_codigo,$params);            
                redirect('permxrol/index');
            }
            else
            {   
                $data['permxrol'] = $this->Permxrol_model->get_permxrol($perm_codigo);

                $this->load->view('templates/header');
                $this->load->view('permxrol/edit', $data);
                $this->load->view('templates/footer');
            }
        }
        else
            show_error('The permxrol you are trying to edit does not exist.');
    } 

    /*
     * Deleting permxrol
     */
    function remove($perm_codigo)
    {
        $permxrol = $this->Permxrol_model->get_permxrol($perm_codigo);

        // check if the permxrol exists before trying to delete it
        if(isset($permxrol['perm_codigo']))
        {
            $this->Permxrol_model->delete_permxrol($perm_codigo);
            redirect('permxrol/index');
        }
        else
            show_error('The permxrol you are trying to delete does not exist.');
    }
    
}
