<?php

/*
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Plan_de_estudio extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Plan_de_estudio_model');
    }

    /*
     * Listing of planes_de_estudio
     */

    private $limit = 5;

    function index()
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $data['planes_de_estudio'] = $this->Plan_de_estudio_model->get_all_planes_de_estudio();

            /*Empiezo de paginacion*/
            $total_rows = $this->Plan_de_estudio_model->count();

            $this->load->library('pagination');
            $config['total_rows'] = $total_rows;
            $config['per_page'] = $this->limit;
            $config['uri_segment'] = 3;
            $config['base_url'] = base_url() . '/plan_de_estudio/index';
            //CSS
            $config['full_tag_open'] = '<ul class="tsc_pagination tsc_paginationA tsc_paginationA01">';
            $config['full_tag_close'] = '</ul>';
            $config['prev_link'] = '&lt;';
            $config['prev_tag_open'] = '<li>';
            $config['prev_tag_close'] = '</li>';
            $config['next_link'] = '&gt;';
            $config['next_tag_open'] = '<li>';
            $config['next_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="current"><a href="#">';
            $config['cur_tag_close'] = '</a></li>';
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';

            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $config['first_link'] = '&lt;&lt;';
            $config['last_link'] = '&gt;&gt;';
            //Fin CSS
            $this->pagination->initialize($config);

            $page_links = $this->pagination->create_links();
            $data['links'] = explode('&nbsp;', $page_links);
            /*Fin de paginacion*/

            $this->load->helper('form');
            $this->load->helper(array('form'));
            $this->load->view('templates/header');
            $this->load->view('plan_de_estudio/index', $data);
            $this->load->view('templates/footer');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

    /*
     * Adding a new plan_de_estudio
     */
    function add()
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $this->load->library('form_validation');

            $this->form_validation->set_rules('carr_codigo', 'Codigo Carrera', 'required|integer');
            $this->form_validation->set_rules('plan_descripcion', 'Descripcion Plan de Estudio', 'required');

            if ($this->form_validation->run()) {
                //Agregado
                $this->db->select_max('plan_codigo');
                $result = $this->db->get('plan_de_estudio')->row_array();
                //
                $params = array(
                    //agregado
                    'plan_codigo' => $result['plan_codigo'] + 1,
                    //
                    'carr_codigo' => $this->input->post('carr_codigo'),
                    'plan_descripcion' => $this->input->post('plan_descripcion'),
                    'plan_fechainicio' => $this->input->post('plan_fechainicio'),
                    'plan_vigencia' => $this->input->post('plan_vigencia'),
                );

                $plan_de_estudio_id = $this->Plan_de_estudio_model->add_plan_de_estudio($params);
                redirect('plan_de_estudio/index');
            } else {

                $this->load->model('Carrera_model');
                $data['all_carreras'] = $this->Carrera_model->get_all_carreras_();

                $this->load->view('templates/header');
                $this->load->view('plan_de_estudio/add', $data);
                $this->load->view('templates/footer');
            }

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

    /*
     * Editing a plan_de_estudio
     */
    function edit($plan_codigo)
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            // check if the plan_de_estudio exists before trying to edit it
            $plan_de_estudio = $this->Plan_de_estudio_model->get_plan_de_estudio($plan_codigo);

            if (isset($plan_de_estudio['plan_codigo'])) {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('carr_codigo', 'Carr Codigo', 'required|integer');
                $this->form_validation->set_rules('plan_descripcion', 'Plan Descripcion', 'required');

                if ($this->form_validation->run()) {
                    $params = array(
                        'carr_codigo' => $this->input->post('carr_codigo'),
                        'plan_descripcion' => $this->input->post('plan_descripcion'),
                        'plan_fechainicio' => $this->input->post('plan_fechainicio'),
                        'plan_vigencia' => $this->input->post('plan_vigencia'),
                    );

                    $this->Plan_de_estudio_model->update_plan_de_estudio($plan_codigo, $params);
                    redirect('plan_de_estudio/index');
                } else {
                    $data['plan_de_estudio'] = $this->Plan_de_estudio_model->get_plan_de_estudio($plan_codigo);

                    $this->load->model('Carrera_model');
                    $data['all_carreras'] = $this->Carrera_model->get_all_carreras_();

                    $this->load->view('templates/header');
                    $this->load->view('plan_de_estudio/edit', $data);
                    $this->load->view('templates/footer');
                }
            } else
                show_error('The plan_de_estudio you are trying to edit does not exist.');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

    /*
     * Deleting plan_de_estudio
     */
    function remove($plan_codigo)
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $plan_de_estudio = $this->Plan_de_estudio_model->get_plan_de_estudio($plan_codigo);

            // check if the plan_de_estudio exists before trying to delete it
            if (isset($plan_de_estudio['plan_codigo'])) {
                $this->Plan_de_estudio_model->delete_plan_de_estudio($plan_codigo);
                redirect('plan_de_estudio/index');
            } else
                show_error('The plan_de_estudio you are trying to delete does not exist.');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

}
