<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Responsable_titulacion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Responsable_titulacion_model');
    } 

    /*
     * Listing of responsables_titulacion
     */
    function index()
    {
        $data['responsables_titulacion'] = $this->Responsable_titulacion_model->get_all_responsables_titulacion();

        $this->load->view('responsables_titulacion/index',$data);
    }

    /*
     * Adding a new responsable_titulacion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('per_codigo','Per Codigo','required|integer');
		$this->form_validation->set_rules('res_tipo','Res Tipo','required|max_length[2]');
		$this->form_validation->set_rules('res_fechanombramiento','Res Fechanombramiento','required');
		
		if($this->form_validation->run())     
        {   $this->db->select_max('res_codigo');
            $result=$this->db->get('responsables_titulacion')->row_array();
            $params = array(
                'res_codigo' => $result['res_codigo']+1,
				'per_codigo' => $this->input->post('per_codigo'),
				'res_tipo' => $this->input->post('res_tipo'),
				'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
            );
            
            $responsable_titulacion_id = $this->Responsable_titulacion_model->add_responsable_titulacion($params);
            redirect('responsable_titulacion/index');
        }
        else
        {

			$this->load->model('Profesor_model');
			$data['all_profesores'] = $this->Profesor_model->get_all_profesores();
                
            $this->load->view('responsables_titulacion/add',$data);
        }
    }  

    /*
     * Editing a responsable_titulacion
     */
    function edit($res_codigo)
    {   
        // check if the responsable_titulacion exists before trying to edit it
        $responsable_titulacion = $this->Responsable_titulacion_model->get_responsable_titulacion($res_codigo);
        
        if(isset($responsable_titulacion['res_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('per_codigo','Per Codigo','required|integer');
			$this->form_validation->set_rules('res_tipo','Res Tipo','required|max_length[2]');
			$this->form_validation->set_rules('res_fechanombramiento','Res Fechanombramiento','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'per_codigo' => $this->input->post('per_codigo'),
					'res_tipo' => $this->input->post('res_tipo'),
					'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
                );

                $this->Responsable_titulacion_model->update_responsable_titulacion($res_codigo,$params);            
                redirect('responsable_titulacion/index');
            }
            else
            {   
                $data['responsable_titulacion'] = $this->Responsable_titulacion_model->get_responsable_titulacion($res_codigo);
    
				$this->load->model('Profesor_model');
				$data['all_profesores'] = $this->Profesor_model->get_all_profesores();

                $this->load->view('responsables_titulacion/edit',$data);
            }
        }
        else
            show_error('The responsable_titulacion you are trying to edit does not exist.');
    } 

    /*
     * Deleting responsable_titulacion
     */
    function remove($res_codigo)
    {
        $responsable_titulacion = $this->Responsable_titulacion_model->get_responsable_titulacion($res_codigo);

        // check if the responsable_titulacion exists before trying to delete it
        if(isset($responsable_titulacion['res_codigo']))
        {
            $this->Responsable_titulacion_model->delete_responsable_titulacion($res_codigo);
            redirect('responsable_titulacion/index');
        }
        else
            show_error('The responsable_titulacion you are trying to delete does not exist.');
    }
    
}
