<?php

/*
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Responsables_titulacion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Responsables_titulacion_model');
    }

    /*
     * Listing of responsables_titulacion
     */

    private $limit = 5;

    function index()
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $data['responsables_titulacion'] = $this->Responsables_titulacion_model->get_all_responsables_titulacion();

            /*Empiezo de paginacion*/
            $total_rows = $this->Responsables_titulacion_model->count();

            $this->load->library('pagination');
            $config['total_rows'] = $total_rows;
            $config['per_page'] = $this->limit;
            $config['uri_segment'] = 3;
            $config['base_url'] = base_url() . '/responsables_titulacion/index';
            //CSS
            $config['full_tag_open'] = '<ul class="tsc_pagination tsc_paginationA tsc_paginationA01">';
            $config['full_tag_close'] = '</ul>';
            $config['prev_link'] = '&lt;';
            $config['prev_tag_open'] = '<li>';
            $config['prev_tag_close'] = '</li>';
            $config['next_link'] = '&gt;';
            $config['next_tag_open'] = '<li>';
            $config['next_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="current"><a href="#">';
            $config['cur_tag_close'] = '</a></li>';
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';

            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $config['first_link'] = '&lt;&lt;';
            $config['last_link'] = '&gt;&gt;';
            //Fin CSS
            $this->pagination->initialize($config);

            $page_links = $this->pagination->create_links();
            $data['links'] = explode('&nbsp;', $page_links);
            /*Fin de paginacion*/

            $this->load->helper('form');
            $this->load->helper(array('form'));
            $this->load->view('templates/header');
            $this->load->view('responsables_titulacion/index', $data);
            $this->load->view('templates/footer');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }
    function buscarResponsableTitulacion()
    {

        if (isset($_SERVER['HTTP_REFERER'])) {
            $data['responsables_titulacion'] = $this->Responsables_titulacion_model->getResponsableTitulacionBusqueda($this->input->post('search'));

            /*Empiezo de paginacion*/
            $total_rows = $this->Responsables_titulacion_model->countParamSearch($this->input->post('search'));

            $this->load->library('pagination');
            //   $config['total_rows'] = $total_rows;
            $config['per_page'] = 5;
            $config['uri_segment'] = 3;
            $config['base_url'] = base_url() . '/responsables_titulacion/buscarResponsableTitulacion';


            //CSS
            $config['full_tag_open'] = '<ul class="tsc_pagination tsc_paginationA tsc_paginationA01">';
            $config['full_tag_close'] = '</ul>';
            $config['prev_link'] = '&lt;';
            $config['prev_tag_open'] = '<li>';
            $config['prev_tag_close'] = '</li>';
            $config['next_link'] = '&gt;';
            $config['next_tag_open'] = '<li>';
            $config['next_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="current"><a href="#">';
            $config['cur_tag_close'] = '</a></li>';
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';

            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $config['first_link'] = '&lt;&lt;';
            $config['last_link'] = '&gt;&gt;';
            //Fin CSS
            $this->pagination->initialize($config);

            $page_links = $this->pagination->create_links();
            $data['links'] = explode('&nbsp;', $page_links);
            /*Fin de paginacion*/


            $this->load->helper('form');
            $this->load->helper(array('form'));
            $this->load->view('templates/header');
            $this->load->view('responsables_titulacion/index', $data);
            $this->load->view('templates/footer');
        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }
    /*
     * Adding a new responsables_titulacion
     */
    function add()
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $this->load->library('form_validation');

            $this->form_validation->set_rules('res_tipo', 'Tipo de Responsable', 'required|max_length[2]');
            $this->form_validation->set_rules('res_fechanombramiento', 'Fecha de Nombramiento', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'prof_codigo' => $this->input->post('prof_codigo'),
                    'res_tipo' => $this->input->post('res_tipo'),
                    'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
                );

                $responsables_titulacion_id = $this->Responsables_titulacion_model->add_responsables_titulacion($params);
                redirect('responsables_titulacion/index');
            } else {

                $this->load->model('Profesor_model');
                $data['all_profesores'] = $this->Profesor_model->get_all_profesores_();

                $this->load->view('templates/header');
                $this->load->view('responsables_titulacion/add', $data);
                $this->load->view('templates/footer');
            }

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

    /*
     * Editing a responsables_titulacion
     */
    function edit($res_codigo)
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            // check if the responsables_titulacion exists before trying to edit it
            $responsables_titulacion = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);

            if (isset($responsables_titulacion['res_codigo'])) {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('res_tipo', 'Tipo de Responsable', 'required|max_length[2]');
                $this->form_validation->set_rules('res_fechanombramiento', 'Fecha de Nombramiento', 'required');

                if ($this->form_validation->run()) {
                    $params = array(
                        'prof_codigo' => $this->input->post('prof_codigo'),
                        'res_tipo' => $this->input->post('res_tipo'),
                        'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
                    );

                    $this->Responsables_titulacion_model->update_responsables_titulacion($res_codigo, $params);
                    redirect('responsables_titulacion/index');
                } else {
                    $data['responsables_titulacion'] = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);

                    $this->load->model('Profesor_model');
                    $data['all_profesores'] = $this->Profesor_model->get_all_profesores_();

                    $this->load->view('templates/header');
                    $this->load->view('responsables_titulacion/edit', $data);
                    $this->load->view('templates/footer');
                }
            } else
                show_error('The responsables_titulacion you are trying to edit does not exist.');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

    /*
     * Deleting responsables_titulacion
     */
    function remove($res_codigo)
    {
        if (isset($_SERVER['HTTP_REFERER'])) {

            $responsables_titulacion = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);

            // check if the responsables_titulacion exists before trying to delete it
            if (isset($responsables_titulacion['res_codigo'])) {
                $this->Responsables_titulacion_model->delete_responsables_titulacion($res_codigo);
                redirect('responsables_titulacion/index');
            } else
                show_error('The responsables_titulacion you are trying to delete does not exist.');

        } else {


            $this->load->view('templates/header');
            $this->load->view('templates/forbidden');
            $this->load->view('templates/footer');

        }
    }

}
