<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Responsables_titulacion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Responsables_titulacion_model');
    } 

    /*
     * Listing of responsables_titulacion
     */
    function index()
    {
        $data['responsables_titulacion'] = $this->Responsables_titulacion_model->get_all_responsables_titulacion();

        $this->load->view('responsables_titulacion/index',$data);
    }

    /*
     * Adding a new responsables_titulacion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('res_tipo','Res Tipo','required|max_length[2]');
		$this->form_validation->set_rules('res_fechanombramiento','Res Fechanombramiento','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'prof_codigo' => $this->input->post('prof_codigo'),
				'res_tipo' => $this->input->post('res_tipo'),
				'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
            );
            
            $responsables_titulacion_id = $this->Responsables_titulacion_model->add_responsables_titulacion($params);
            redirect('responsables_titulacion/index');
        }
        else
        {

			$this->load->model('Profesor_model');
			$data['all_profesores'] = $this->Profesor_model->get_all_profesores();
                
            $this->load->view('responsables_titulacion/add',$data);
        }
    }  

    /*
     * Editing a responsables_titulacion
     */
    function edit($res_codigo)
    {   
        // check if the responsables_titulacion exists before trying to edit it
        $responsables_titulacion = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);
        
        if(isset($responsables_titulacion['res_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('res_tipo','Res Tipo','required|max_length[2]');
			$this->form_validation->set_rules('res_fechanombramiento','Res Fechanombramiento','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'prof_codigo' => $this->input->post('prof_codigo'),
					'res_tipo' => $this->input->post('res_tipo'),
					'res_fechanombramiento' => $this->input->post('res_fechanombramiento'),
                );

                $this->Responsables_titulacion_model->update_responsables_titulacion($res_codigo,$params);            
                redirect('responsables_titulacion/index');
            }
            else
            {   
                $data['responsables_titulacion'] = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);
    
				$this->load->model('Profesor_model');
				$data['all_profesores'] = $this->Profesor_model->get_all_profesores();

                $this->load->view('responsables_titulacion/edit',$data);
            }
        }
        else
            show_error('The responsables_titulacion you are trying to edit does not exist.');
    } 

    /*
     * Deleting responsables_titulacion
     */
    function remove($res_codigo)
    {
        $responsables_titulacion = $this->Responsables_titulacion_model->get_responsables_titulacion($res_codigo);

        // check if the responsables_titulacion exists before trying to delete it
        if(isset($responsables_titulacion['res_codigo']))
        {
            $this->Responsables_titulacion_model->delete_responsables_titulacion($res_codigo);
            redirect('responsables_titulacion/index');
        }
        else
            show_error('The responsables_titulacion you are trying to delete does not exist.');
    }
    
}
