<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Rev_dir_trab_titulacion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rev_dir_trab_titulacion_model');
    } 

    /*
     * Listing of rev_dir_trab_titulacion
     */
    function index()
    {
        $data['rev_dir_trab_titulacion'] = $this->Rev_dir_trab_titulacion_model->get_all_rev_dir_trab_titulacion();

        $this->load->view('rev_dir_trab_titulacion/index',$data);
    }

    /*
     * Adding a new rev_dir_trab_titulacion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('per_codigo','Per Codigo','required|integer');
		$this->form_validation->set_rules('red_tipo','Red Tipo','required|max_length[3]');
		$this->form_validation->set_rules('red_fechanombramiento','Red Fechanombramiento','required');
		
		if($this->form_validation->run())     
        {
            $this->db->select_max('red_codigo');
            $result=$this->db->get('rev_dir_trab_titulacion')->row_array();
            $params = array(
                'red_codigo' => $result['red_codigo']+1,
				'per_codigo' => $this->input->post('per_codigo'),
				'red_tipo' => $this->input->post('red_tipo'),
				'red_fechanombramiento' => $this->input->post('red_fechanombramiento'),
            );
            
            $rev_dir_trab_titulacion_id = $this->Rev_dir_trab_titulacion_model->add_rev_dir_trab_titulacion($params);
            redirect('rev_dir_trab_titulacion/index');
        }
        else
        {

			$this->load->model('Profesor_model');
			$data['all_profesores'] = $this->Profesor_model->get_all_profesores();
                
            $this->load->view('rev_dir_trab_titulacion/add',$data);
        }
    }  

    /*
     * Editing a rev_dir_trab_titulacion
     */
    function edit($red_codigo)
    {   
        // check if the rev_dir_trab_titulacion exists before trying to edit it
        $rev_dir_trab_titulacion = $this->Rev_dir_trab_titulacion_model->get_rev_dir_trab_titulacion($red_codigo);
        
        if(isset($rev_dir_trab_titulacion['red_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('per_codigo','Per Codigo','required|integer');
			$this->form_validation->set_rules('red_tipo','Red Tipo','required|max_length[3]');
			$this->form_validation->set_rules('red_fechanombramiento','Red Fechanombramiento','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'per_codigo' => $this->input->post('per_codigo'),
					'red_tipo' => $this->input->post('red_tipo'),
					'red_fechanombramiento' => $this->input->post('red_fechanombramiento'),
                );

                $this->Rev_dir_trab_titulacion_model->update_rev_dir_trab_titulacion($red_codigo,$params);            
                redirect('rev_dir_trab_titulacion/index');
            }
            else
            {   
                $data['rev_dir_trab_titulacion'] = $this->Rev_dir_trab_titulacion_model->get_rev_dir_trab_titulacion($red_codigo);
    
				$this->load->model('Profesor_model');
				$data['all_profesores'] = $this->Profesor_model->get_all_profesores();

                $this->load->view('rev_dir_trab_titulacion/edit',$data);
            }
        }
        else
            show_error('The rev_dir_trab_titulacion you are trying to edit does not exist.');
    } 

    /*
     * Deleting rev_dir_trab_titulacion
     */
    function remove($red_codigo)
    {
        $rev_dir_trab_titulacion = $this->Rev_dir_trab_titulacion_model->get_rev_dir_trab_titulacion($red_codigo);

        // check if the rev_dir_trab_titulacion exists before trying to delete it
        if(isset($rev_dir_trab_titulacion['red_codigo']))
        {
            $this->Rev_dir_trab_titulacion_model->delete_rev_dir_trab_titulacion($red_codigo);
            redirect('rev_dir_trab_titulacion/index');
        }
        else
            show_error('The rev_dir_trab_titulacion you are trying to delete does not exist.');
    }
    
}
