<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Revdir_x_disertacion extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Revdir_x_disertacion_model');
    } 

    /*
     * Listing of revdir_x_disertacion
     */
    function index()
    {
        $data['revdir_x_disertacion'] = $this->Revdir_x_disertacion_model->get_all_revdir_x_disertacion();

        $this->load->view('revdir_x_disertacion/index',$data);
    }

    /*
     * Adding a new revdir_x_disertacion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rxd_tipo','Rxd Tipo','required|max_length[3]');
		$this->form_validation->set_rules('rxd_fechanombramiento','Rxd Fechanombramiento','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'rxd_tipo' => $this->input->post('rxd_tipo'),
				'rxd_fechanombramiento' => $this->input->post('rxd_fechanombramiento'),
            );
            
            $revdir_x_disertacion_id = $this->Revdir_x_disertacion_model->add_revdir_x_disertacion($params);
            redirect('revdir_x_disertacion/index');
        }
        else
        {
            $this->load->view('revdir_x_disertacion/add');
        }
    }  

    /*
     * Editing a revdir_x_disertacion
     */
    function edit($dis_codigo,$prof_codigo)
    {   
        // check if the revdir_x_disertacion exists before trying to edit it
        $revdir_x_disertacion = $this->Revdir_x_disertacion_model->get_revdir_x_disertacion($dis_codigo,$prof_codigo);
        
        if(isset($revdir_x_disertacion['dis_codigo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('rxd_tipo','Rxd Tipo','required|max_length[3]');
			$this->form_validation->set_rules('rxd_fechanombramiento','Rxd Fechanombramiento','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'rxd_tipo' => $this->input->post('rxd_tipo'),
					'rxd_fechanombramiento' => $this->input->post('rxd_fechanombramiento'),
                );

                $this->Revdir_x_disertacion_model->update_revdir_x_disertacion($dis_codigo,$params);            
                redirect('revdir_x_disertacion/index');
            }
            else
            {   
                $data['revdir_x_disertacion'] = $this->Revdir_x_disertacion_model->get_revdir_x_disertacion($dis_codigo);
    
                $this->load->view('revdir_x_disertacion/edit',$data);
            }
        }
        else
            show_error('The revdir_x_disertacion you are trying to edit does not exist.');
    } 

    /*
     * Deleting revdir_x_disertacion
     */
    function remove($dis_codigo,$prof_codigo)
    {
        $revdir_x_disertacion = $this->Revdir_x_disertacion_model->get_revdir_x_disertacion($dis_codigo,$prof_codigo);

        // check if the revdir_x_disertacion exists before trying to delete it
        if(isset($revdir_x_disertacion['dis_codigo']))
        {
            $this->Revdir_x_disertacion_model->delete_revdir_x_disertacion($dis_codigo,$prof_codigo);
            redirect('revdir_x_disertacion/index');
        }
        else
            show_error('The revdir_x_disertacion you are trying to delete does not exist.');
    }
    
}
