insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (9, 'Fisica', 1);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (5, 'Introduccion a la computacion', 15);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (17, 'Geometria', 14);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (8, 'Bases de Datos', 9);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (6, 'Programacion Basica', 10);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (10, 'Algebra Lineal', 0);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (18, 'POO', 7);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (2, 'Estadistica', 3);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (11, 'Electrologia', 2);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (15, 'Matematicas Basicas', 5);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (3, 'Matematicas Discretas', 19);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (1, 'Estructura de Datos I', 6);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (19, 'Estructura de Datos II', 16);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (13, 'Ingenieria de Software I', 13);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (7, 'Ingenieria de Software II', 12);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (16, 'Sistemas Operativos', 11);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (4, 'Diseño de Sisetmas Operativos', 18);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (12, 'EDO', 8);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (14, 'Nuevas Tecnicas de Progamacion', 4);

insert into MATERIAS (MAT_CODIGO, MAT_NOMBRE, MAT_NIVEL) values (0, 'Jesus', 17);

insert into PERMISOS (PERM_CODIGO, PERM_ESTADO, PERM_CREAT, PERM_READ, PERM_UPDATE, PERM_DELETE) values (1, TRUE, TRUE, TRUE, TRUE, TRUE); 

insert into PERMISOS (PERM_CODIGO, PERM_ESTADO, PERM_CREAT, PERM_READ, PERM_UPDATE, PERM_DELETE) values (2, TRUE, TRUE, TRUE, TRUE, FALSE);

insert into PERMISOS (PERM_CODIGO, PERM_ESTADO, PERM_CREAT, PERM_READ, PERM_UPDATE, PERM_DELETE) values (3, TRUE, FALSE, TRUE, FALSE, FALSE);

insert into PERMISOS (PERM_CODIGO, PERM_ESTADO, PERM_CREAT, PERM_READ, PERM_UPDATE, PERM_DELETE) values (4, TRUE, FALSE, TRUE, TRUE, FALSE);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (5, 'Periodo1', '2016-11-27', '2017-10-29', 16);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (14, 'Periodo2', '1262-3-11', '2017-10-22', 12);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (8, 'Periodo3', '1016-1-8', '1164-9-13', 17);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (2, 'Periodo4', '2016-11-13', '2017-3-22', 19);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (9, 'Periodo5', '2016-12-6', '2017-11-23', 5);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (17, 'Periodo6', '2016-1-4', '2017-2-4', 14);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (10, 'Periodo7', '2016-7-24', '2017-1-1', 10);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (7, 'Periodo8', '2016-12-30', '2017-9-4', 7);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (16, 'Periodo9', '2016-5-4', '2017-6-7', 11);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (4, 'Periodo10', '2016-7-30', '2017-2-9', 0);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (19, 'Periodo11', '1572-3-23', '2016-7-5', 3);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (15, 'Periodo12', '1191-7-11', '2017-2-22', 4);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (6, 'Periodo13', '1488-8-31', '1629-5-1', 15);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (3, 'Periodo14', '1-1-1', '2016-3-17', 18);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (18, 'Periodo15', '308-2-18', '1030-8-12', 9);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (0, 'Periodo16', '1068-5-7', '2016-3-6', 6);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (13, 'Periodo17', '114-12-4', '1489-12-26', 13);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (12, 'Periodo18', '1777-10-12', '2016-10-8', 2);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (1, 'Periodo19', '678-7-1', '2016-3-21', 8);

insert into PERIODOS_ACADEMICOS (PAC_CODIGO, PAC_DESCRIPCION, PAC_FECHAINICIO, PAC_FECHAFINAL, PAC_PERIDO) values (11, 'Periodo20', '973-9-12', '2016-5-17', 1);

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (15, 'Ingenieria');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (19, 'Medicina');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (16, 'Comunicacion');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (17, 'Administracion');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (18, 'Economia');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (14, 'Teologia');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (7, 'Biologia');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (13, 'Ciencias Exactas');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (10, 'Facultad1');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (0, 'Facultad3');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (1, 'Facultad4');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (6, 'Facultad5');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (2, 'Facultad6');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (9, 'Facultad2');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (4, 'Facultad7');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (12, 'Facultad8');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (11, 'Facultad9');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (8, 'Facultad10');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (3, 'Facultad12');

insert into FACULTADES (FACU_CODIGO, FACU_DESCRIPCION) values (5, 'Facultad13');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (6, 15, 'Sistemas');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (5, 16, 'Civil');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (1, 19, 'Bioquimica');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (15, 1, 'Literatura');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (19, 0, 'Relaciones Internacionales');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (7, 10, 'Sociologia');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (0, 16, 'Mercadeo');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (18, 0, 'Contabilidad');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (11, 4, 'MacroEconomia');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (14, 1, 'Escuela11');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (9, 7, 'Escuela10');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (17, 3, 'Escuela1');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (3, 18, 'Escuela3');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (2, 19, 'Escuela2');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (4, 16, 'Escuela4');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (12, 2, 'Escuela5');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (10, 13, 'Escuela6');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (8, 3, 'Escuela7');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (13, 13, 'Escuela8');

insert into ESCUELAS (ESC_CODIGO, FACU_CODIGO, ESC_DESCRIPCION) values (16, 17, 'Escuela9');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (13, 6, 'Sistemas y Computacion');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (10, 0, 'Periodismo');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (19, 12, 'Matematicas exactas');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (12, 1, 'Musica Contemporanea');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (9, 19, 'Ciencias de la computacion');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (5, 2, 'Diseño Grafico');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (14, 13, 'Carrera1');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (7, 2, 'Carrera2');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (11, 2, 'Carrera3');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (16, 18, 'Carrera4');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (17, 11, 'Carrera5');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (3, 11, 'Carrera6');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (6, 4, 'Carrera7');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (0, 14, 'Carrera8');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (8, 10, 'Carrera9');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (18, 11, 'Carrera10');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (4, 0, 'Carrera11');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (15, 10, 'Carrera12');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (1, 17, 'Carrera13');

insert into CARRERAS (CARR_CODIGO, ESC_CODIGO, CARR_DESCRIPCION) values (2, 13, 'Carrera14');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (1, 'Administrador');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (2, 'Director');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (3, 'Profesor');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (4, 'Estudiante');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (5, 'Decano');

insert into ROLES (ROL_CODIGO, ROL_DESCRIPCION) values (6, 'Revisor');

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (1, 1);

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (2, 2);

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (3, 3);

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (4, 3);

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (5, 3);

insert into PERMXROL (ROL_CODIGO, PERM_CODIGO) values (6, 4);

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (1, 'Modulo Administrador');

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (2, 'Modulo Director');

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (3, 'Modulo Profesor');

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (4, 'Modulo Estudiante');

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (5, 'Modulo Decano');

insert into MODULO (MOD_CODIGO, MOD_DESCRIPCION) values (6, 'Modulo Revisor');

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (1, 1);

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (2, 2);

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (3, 3);

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (4, 4);

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (5, 5);

insert into MODXROL (ROL_CODIGO, MOD_CODIGO) values (6, 6);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (1, 13, 'PlanEst1', '2017-4-15', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (11, 7, 'PlanEst2', '2017-6-14', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (0, 14, 'PlanEst3', '2017-6-20', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (5, 12, 'PlanEst4', '1253-9-4', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (15, 11, 'PlanEst5', '1500-10-1', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (2, 9, 'PlanEst6', '2017-12-31', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (19, 7, 'PlanEst7', '2017-2-17', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (4, 7, 'PlanEst8', '1594-3-19', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (3, 6, 'PlanEst9', '1123-8-27', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (16, 4, 'PlanEst10', '1024-12-17', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (6, 0, 'PlanEst11', '2016-12-10', TRUE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (7, 6, 'PlanEst12', '2017-3-10', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (13, 11, 'PlanEst13', '2017-6-15', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (14, 18, 'PlanEst14', '262-10-23', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (18, 8, 'PlanEst15', '684-12-24', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (9, 5, 'PlanEst16', '1447-2-3', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (17, 15, 'PlanEst17', '2016-1-1', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (12, 12, 'PlanEst18', '2016-3-5', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (8, 18, 'PlanEst19', '2016-5-17', FALSE);

insert into PLAN_DE_ESTUDIO (PLAN_CODIGO, CARR_CODIGO, PLAN_DESCRIPCION, PLAN_FECHAINICIO, PLAN_VIGENCIA) values (10, 5, 'PlanEst20', '2016-1-1', FALSE);

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (3,  13, 'Juan', 'Daniel', 'Mena', 'Cazares', 'RUC', '1231123222', 'Comite del Pueblo', '42342422', '093486533', 'est1@mail.com', 'puceest2@mail.com', '2016-1-9', 'M', 'Foto',  '2016-12-19', '2017-4-21', '2018-10-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (11,  8, 'Carlos', 'Andres', 'Paez', 'Lewandoski', 'RUC', '124123222', 'Guamani', '4042422', '0976786533', 'est2@mail.com', 'puceest3@mail.com', '2016-10-9', 'M', 'Foto',  '2017-12-19', '5220-4-21', '2017-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (10,  9, 'David', 'Luis', 'Ginez', 'Messi', 'CED', '1636323222', 'Atahualpa', '32342422', '0976786533', 'est3@mail.com', 'puceest4@mail.com', '504-12-9', 'M', 'Foto',  '2008-12-19', '2013-4-22', '2016-11-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (19, 15, 'Daniel', 'Fernando', 'Perez', 'Bolaños', 'CED', '1097823222', 'Cumbaya', '22342422', '097600033', 'est4@mail.com', 'puceest1@mail.com', '504-11-9', 'M', 'Foto',  '2017-12-19', '2017-8-22', '2016-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (12,  6, 'Patricio', 'Alexander', 'Palma', 'Banguera', 'CED', '876723222', 'Lumbisi', '42349922', '0976786533', 'est5@mail.com', 'puceest5@mail.com', '504-10-9', 'M', 'Foto',  '2010-12-19', '2017-4-26', '2013-5-8');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (7,  14, 'Henry', 'Sergio', 'Mena', 'Pancho', 'CED', '12318286522', 'El Batan', '42342422', '0976786533', 'est6@mail.com', 'puceest6@mail.com', '504-8-9', 'M', 'Foto',  '2009-12-19', '2016-4-21', '2016-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (13,  17, 'Gonzalo', 'Andres', 'Rosero', 'Lasso', 'CED', '1235454222', 'Carcelen', '42342422', '0976786533', 'est7@mail.com', 'puceest8@mail.com', '2017-7-7', 'M', 'Foto',  '2008-12-19', '2016-11-21', '2017-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (2,  1, 'Roberto', 'Daniel', 'Valencia', 'Noboa', 'CED', '122422222', 'Calderon', '42342422', '097677533', 'est8@mail.com', 'puceest7@mail.com', '2015-1-9', 'M', 'Foto',  '2011-12-19', '2016-4-21', '2017-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (18,  10, 'Luis', 'Andres', 'Diaz', 'Lasso', 'RUC', '195665622', 'Comite del Pueblo', '42662422', '0978787633', 'est9@mail.com', 'puceest9@mail.com', '504-1-9', 'M', 'Foto',  '2009-12-19', '2015-4-10', '2016-6-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (15,  15, 'Francisco', 'Fernando', 'Cordova', 'Guerron', 'RUC', '1112322', 'Comite del Pueblo', '42342422', '0965578533', 'est10@mail.com', 'puceest10@mail.com', '504-1-9', 'M', 'Foto',  '2010-12-19', '2013-4-10', '2014-6-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (6,  4, 'Diego', 'Andres', 'Mena', 'Correa', 'RUC', '188883453', 'Calderon', '42342422', '0976786533', 'est11@mail.com', 'puceest11@mail.com', '2015-1-8', 'M', 'Foto',  '2007-12-19', '2017-4-21', '2017-5-10');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (9,  11, 'Erick', 'Luis', 'Mena', 'Chiriboga', 'CED', '1023425233', 'Atahualpa', '42301422', '0976786533', 'est12@mail.com', 'puceest12@mail.com', '504-5-9', 'M', 'Foto',  '2010-12-19', '2015-3-10', '2016-5-25');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (0,  5, 'Paula', 'Antonella', 'Yanez', 'Montoya', 'CED', '1123233333', 'Comite del Pueblo', '42342422', '0976786533', 'est13@mail.com', 'puceest13@mail.com', '504-1-9', 'F', 'Foto', '2008-12-19', '2016-9-21', '2016-5-25');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (16,  15, 'Gabriela', 'Domenica', 'Loza', 'Bucaram', 'RUC', '185646633', 'Comite del Pueblo', '42342422', '0976786533', 'est14@mail.com', 'puceest14@mail.com', '504-1-9', 'F', 'Foto',  '2016-10-19', '2016-4-21', '2016-4-25');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (8,  14, 'Maria', 'Antonieta', 'Mena', 'Varela', 'CED', '868457363', 'Atahualpa', '42342422', '0976786533', 'est15@mail.com', 'puceest17@mail.com', '2017-2-9', 'F', 'Foto',  '2010-12-19', '2017-4-21', '2017-5-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (17,  13, 'Susana', 'Michelle', 'Aimar', 'Olivo', 'CED', '044635223422', 'Calderon', '42333422', '0976786533', 'est16@mail.com', 'puceest15@mail.com', '2015-4-2', 'F', 'Foto',  '2011-8-19', '2016-4-10', '2017-2-16');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (1,  13, 'Jose', 'Andres', 'Alvez', 'Simbaña', 'CED', '112213123123', 'Comite del Pueblo', '42342422', '0976786533', 'est17@mail.com', 'puceest16@mail.com', '504-1-9', 'M', 'Foto',  '2016-12-19', '2017-4-21', '2017-2-11');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (4,  14, 'Cristian', 'Alexander', 'Caicedo', 'Rosero', 'RUC', '155525223', 'Comite del Pueblo', '022342422', '0976786533', 'est18@mail.com', 'puceest18@mail.com', '504-1-9', 'M', 'Foto', '2016-12-19', '2017-6-21', '2017-2-16');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (5,  11, 'Dario', 'Daniel', 'Pico', 'Lasso', 'RUC', '19986677343', 'Atahualpa', '00666422', '097670533', 'est19@mail.com', 'puceest19@mail.com', '504-6-9', 'M', 'Foto', '2010-12-19', '2017-7-21', '2017-1-20');

insert into ESTUDIANTE (PER_CODIGO,  CARR_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  EST_FECHAINGRESO, EST_FECHAESTIMADAGRADUACION, EST_FECHAGRADUACION) values (14,  16, 'Cesar', 'Alexander', 'Sierra', 'Lasso', 'RUC', '1874564564', 'Guamani', '42388872', '0976226533', 'est20@mail.com', 'puceest20@mail.com', '504-1-9', 'M', 'Foto', '2009-12-19', '2014-4-21', '2015-5-20');

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (1, 9, 5);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (11, 5, 14);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (0, 17, 8);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (5, 8, 2);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (15, 6, 9);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (2, 10, 17);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (19, 18, 10);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (4, 2, 7);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (3, 11, 16);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (16, 15, 4);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (6, 3, 19);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (7, 1, 15);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (13, 19, 6);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (14, 13, 3);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (18, 7, 18);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (9, 16, 0);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (17, 4, 13);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (12, 12, 12);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (8, 14, 1);

insert into MATERIA_X_PLAN_DE_ESTUDIO (PLAN_CODIGO, MAT_CODIGO, PAC_CODIGO) values (10, 0, 11);

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (8, 'PRONOMBRE11', 'PRONOMBRE21', 'PROAPELLIDO11', 'PROAPELLIDO21', 'CED', '1712323727', 'Atahualpa', '02223443', '0982228382', 'pro1@mail.com', 'pro1puce@mail.com', '2016-10-22', 'M', 'FOTO1', '701');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (11, 'PRONOMBRE12', 'PRONOMBRE22', 'PROAPELLIDO12', 'PROAPELLIDO21', 'CED', '1712000727', 'Carcelen', '02223779', '0987333382', 'pro2@mail.com', 'pro2puce@mail.com', '2016-8-22', 'M', 'FOTO2',  '702');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (16,  'PRONOMBRE13', 'PRONOMBRE23', 'PROAPELLIDO13', 'PROAPELLIDO23', 'CED', '1000872727', 'Carcelen', '02200943', '0987024382', 'pro3@mail.com', 'pro3puce@mail.com', '900-8-22', 'M', 'FOTO1', '703');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (3, 'PRONOMBRE14', 'PRONOMBRE24', 'PROAPELLIDO14', 'PROAPELLIDO24', 'CED', '1734272727', 'Calderon', '01113443', '0987888382', 'pro4@mail.com', 'pro4puce@mail.com', '2016-8-22', 'M', 'FOTO1',  '704');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (9,  'PRONOMBRE15', 'PRONOMBRE25', 'PROAPELLIDO15', 'PROAPELLIDO25', 'RUC', '176572727', 'Villaflora', '02224443', '0911028382', 'pro5@mail.com', 'pro5puce@mail.com', '900-8-18', 'F', 'FOTO1',  '705');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (15,  'PRONOMBRE16', 'PRONOMBRE26', 'PROAPELLIDO16', 'APELLIDO2', 'CED', '1712819727', 'LA MARIN', '02466443', '0999028382', 'pro6@mail.com', 'pro6puce@mail.com', '2016-8-22', 'M', 'FOTO1',  '706');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (13,  'PRONOMBRE17', 'PRONOMBRE28', 'PROAPELLIDO17', 'APELLIDO2', 'RUC', '171342727', 'Calderon', '02228843', '0987000082', 'pro7@mail.com', 'pro7puce@mail.com', '2017-8-18', 'F', 'FOTO1',  '707');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (2,  'PRONOMBRE18', 'PRONOMBRE29', 'PROAPELLIDO18', 'APELLIDO2', 'CED', '1712879897', 'LA MARIN', '02559943', '0987000382', 'pro8@mail.com', 'pro8puce@mail.com', '2016-8-22', 'M', 'FOTO1',  '708');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (7,  'PRONOMBRE19', 'PRONOMBRE210', 'APELLIDO1', 'APELLIDO2', 'RUC', '1712878887', 'Villaflora', '02222243', '0987021382', 'pro9@mail.com', 'pro9puce@mail.com', '900-8-22', 'F', 'FOTO1',  '709');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (5,  'PRONOMBRE110', 'PRONOMBRE211', 'APELLIDO1', 'APELLIDO2', 'CED', '1712234227', 'Calderon', '02223093', '0987095682', 'pro10@mail.com', 'pro10puce@mail.com', '2016-8-22', 'M', 'FOTO1',  '710');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (10,  'PRONOMBRE111', 'PRONOMBRE212', 'APELLIDO1', 'APELLIDO2', 'CED', '1712444727', 'Villaflora', '02217543', '0923428382', 'pro11@mail.com', 'pro11puce@mail.com', '2016-10-22', 'M', 'FOTO1',  '711');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (19,  'PRONOMBRE112', 'PRONOMBRE213', 'APELLIDO1', 'APELLIDO2', 'CED', '1712877777', 'LA MARIN', '02223883', '0987077782', 'pro12@mail.com', 'pro20puce@mail.com', '2017-8-18', 'M', 'FOTO1',  '712');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (1,  'PRONOMBRE113', 'PRONOMBRE214', 'APELLIDO1', 'APELLIDO2', 'CED', '1711112727', 'Calderon', '02223033', '0987028232', 'pro13@mail.com', 'pro12puce@mail.com', '900-8-22', 'M', 'FOTO1',  '713');

insert into PROFESOR (PER_CODIGO,  PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (17,  'PRONOMBRE114', 'PRONOMBRE215', 'APELLIDO1', 'APELLIDO2', 'RUC', '1713442727', 'Villaflora', '02225543', '0989008382', 'pro14@mail.com', 'pro13puce@mail.com', '2017-8-18', 'M', 'FOTO1',  '714');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (4,  'PRONOMBRE115', 'PRONOMBRE216', 'APELLIDO1', 'APELLIDO2', 'CED', '1712833727', 'LA MARIN', '02221943', '0987028123', 'pro15@mail.com', 'pro14puce@mail.com', '2017-10-22', 'M', 'FOTO1',  '715');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,PRO_OFICINA) values (18,  'PRONOMBRE116', 'PRONOMBRE217', 'APELLIDO1', 'APELLIDO2', 'CED', '171290727', 'Villaflora', '02163443', '0983218382', 'pro16@mail.com', 'pro15puce@mail.com', '2017-8-22', 'F', 'FOTO1',  '716');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (14,  'PRONOMBRE117', 'PRONOMBRE218', 'APELLIDO1', 'APELLIDO2', 'CED', '1712872700', 'Calderon', '02228243', '0986628382', 'pro17@mail.com', 'pro16puce@mail.com', '2017-8-22', 'M', 'FOTO1',  '717');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (6,  'PRONOMBRE118', 'PRONOMBRE219', 'APELLIDO1', 'APELLIDO2', 'CED', '171287777', 'LA MARIN', '02264543', '0987078982', 'pro18@mail.com', 'pro17puce@mail.com', '900-8-22', 'M', 'FOTO1',  '718');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO,  PRO_OFICINA) values (12,  'PRONOMBRE119', 'PRONOMBRE220', 'APELLIDO1', 'APELLIDO2', 'CED', '17642727', 'LA MARIN', '02299943', '0983356382', 'pro19@mail.com', 'pro18puce@mail.com', '900-8-22', 'M', 'FOTO1',  '719');

insert into PROFESOR (PER_CODIGO, PER_NOMBRE1, PER_NOMBRE2, PER_APELLIDO1, PER_APELLIDO2, PER_TIPOID, PER_ID, PER_DIRECCION, PER_TELEFONO, PER_CELULAR, PER_MAIL, PER_MAILPUCE, PER_FECHANAC, PER_SEXO, PER_FOTO, PRO_OFICINA) values (0, 'PRONOMBRE120', 'PRONOMBRE2', 'APELLIDO1', 'APELLIDO2', 'CED', '1712872727', 'LA MARIN', '02220543', '0922228382', 'pro20@mail.com', 'pro19puce@mail.com', '900-8-22', 'M', 'FOTO1',  '720');

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (3, 9);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (11, 5);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (10, 17);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (19, 8);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (12, 6);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (7, 10);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (13, 18);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (2, 2);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (18, 11);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (15, 15);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (6, 3);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (9, 1);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (0, 19);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (16, 13);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (8, 7);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (17, 16);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (1, 4);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (4, 12);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (5, 14);

insert into MAT_AP_X_EST (PER_CODIGO, MAT_CODIGO) values (14, 0);

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (4, 3, '2016-5-29', '129-10-13', '741-7-30', 'Titulo1', TRUE, '2016-10-2', '1200-11-6');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (17, 3, '2016-7-27', '1153-1-28', '1467-10-9', 'Titulo2', FALSE, '2016-2-24', '884-11-5');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (19, 9, '2016-2-15', '1649-7-12', '848-10-16', 'Titulo3', TRUE, '2016-9-24', '2017-3-21');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (10, 6, '1721-12-21', '2016-7-26', '1647-12-5', 'Titulo4', FALSE, '1348-12-22', '1664-1-14');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (16, 13, '2016-12-22', '725-12-2', '1197-1-18', 'Titulo5', FALSE, '2016-1-1', '1143-1-25');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (2, 12, '2016-9-18', '2016-4-22', '1816-4-19', 'Titulo6', TRUE, '2016-12-10', '1843-1-5');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (7, 13, '517-12-25', '2016-1-1', '2016-3-16', 'Titulo7', FALSE, '1763-5-7', '2016-7-25');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (11, 0, '2016-6-23', '2016-7-10', '2016-3-9', 'Titulo8', TRUE, '2016-7-12', '250-12-25');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (3, 18, '1262-8-11', '1235-12-14', '1580-7-5', 'Titulo9', TRUE, '1416-3-31', '701-3-1');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (15, 12, '2016-7-18', '2016-4-28', '2016-6-9', 'Titulo10', TRUE, '2016-11-27', '2016-1-14');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (0, 13, '2016-11-5', '2016-10-16', '943-1-11', 'Titulo11', FALSE, '1120-4-13', '2016-12-26');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (5, 9, '602-5-30', '2016-2-14', '2016-6-15', 'Titulo12', TRUE, '2017-4-11', '1320-2-4');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (8, 7, '2016-9-25', '1040-9-18', '473-6-9', 'Titulo13', TRUE, '1210-9-24', '322-5-28');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (6, 1, '2016-9-21', '257-11-18', '1279-9-11', 'Titulo14', FALSE, '1840-5-21', '471-2-17');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (14, 3, '2016-1-1', '1506-3-8', '1766-7-28', 'Titulo15', TRUE, '2016-4-10', '1-1-1');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (18, 15, '1443-9-9', '838-8-26', '2016-10-29', 'Titulo16', TRUE, '1535-11-22', '1030-3-17');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (1, 8, '1654-9-17', '531-12-10', '2016-1-1', 'Titulo17', TRUE, '2016-8-18', '832-9-22');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (13, 4, '2016-11-9', '1378-5-27', '2016-9-28', 'Titulo18', TRUE, '1898-4-8', '967-6-23');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (12, 18, '2016-9-3', '2016-6-26', '1058-9-28', 'Titulo19', FALSE, '1674-1-28', '2017-3-8');

insert into TRABAJO_DISERTACION (DIS_CODIGO, PER_CODIGO, DIS_FECHAINICIO, DIS_FECHAPRESENTACIONPLAN, DIS_FECHAAPROBACION, DIS_TITULO, DIS_ESTADO, DIS_FECHAFIN, DIS_DEFENSA) values (9, 5, '1339-12-2', '1865-5-6', '2016-10-27', 'Titulo20', FALSE, '2017-10-2', '1465-12-21');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (6, 14, 'R2', '2016-9-5');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (14, 11, 'R2', '2016-8-5');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (0, 17, 'R2', '1437-3-9');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (11, 14, 'R2', '1509-6-27');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (8, 16, 'R1', '213-2-2');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (9, 2, 'R1', '2016-12-18');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (12, 16, 'R2', '2016-7-29');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (15, 3, 'R1', '2016-6-2');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (4, 12, 'R1', '2017-2-10');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (10, 4, 'R2', '514-5-28');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (13, 3, 'R1', '711-2-27');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (19, 11, 'R2', '1252-9-8');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (3, 6, 'R1', '101-1-12');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (16, 15, 'R1', '160-7-29');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (17, 14, 'R2', '2017-11-29');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (7, 7, 'R2', '2017-1-14');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (5, 6, 'R1', '2017-1-1');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (2, 4, 'R1', '1188-5-21');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (18, 2, 'R2', '1809-4-2');

insert into RESPONSABLES_TITULACION (RES_CODIGO, PER_CODIGO, RES_TIPO, RES_FECHANOMBRAMIENTO) values (1, 13, 'R2', '2017-1-10');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (19, 12, 'DIR', '923-11-26');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (6, 7, 'R_2', '1-1-1');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (17, 11, 'DIR', '1613-11-20');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (2, 1, 'R_1', '2017-9-26');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (12, 7, 'DIR', '2017-5-20');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (7, 15, 'DIR', '2017-12-18');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (8, 3, 'R_1', '2017-6-10');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (1, 19, 'R_1', '1708-7-10');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (13, 5, 'DIR', '679-8-16');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (18, 17, 'DIR', '1822-6-23');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (0, 3, 'R_1', '2017-8-14');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (9, 17, 'R_2', '1432-12-11');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (10, 19, 'R_1', '299-12-30');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (5, 16, 'DIR', '2017-9-25');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (16, 6, 'R_1', '2017-2-13');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (3, 5, 'R_2', '1174-3-25');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (11, 15, 'R_1', '2017-2-5');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (15, 3, 'R_1', '1542-10-31');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (14, 10, 'R_2', '420-6-14');

insert into REV_DIR_TRAB_TITULACION (RED_CODIGO, PER_CODIGO, RED_TIPO, RED_FECHANOMBRAMIENTO) values (4, 7, 'R_2', '1491-9-5');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (10, 9, '2016-1-1', '297-7-6', '2017-2-11', 'PRORRDESCR1', 'PRORRDETALLE1');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (9, 3, '2016-4-6', '2016-2-24', '2017-6-23', 'PRORRDESCR2', 'PRORRDETALLE2');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (17, 2, '1773-12-31', '2016-3-18', '2017-9-27', 'PRORRDESCR3', 'PRORRDETALLE3');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (16, 2, '2016-9-15', '1322-5-1', '2017-7-19', 'PRORRDESCR4', 'PRORRDETALLE4');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (14, 0, '2016-4-23', '1689-2-6', '2017-1-25', 'PRORRDESCR5', 'PRORRDETALLE5');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (1, 6, '190-12-20', '639-7-20', '1817-7-26', 'PRORRDESCR6', 'PRORRDETALLE6');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (3, 6, '1214-6-13', '1480-9-21', '2017-1-1', 'PRORRDESCR7', 'PRORRDETALLE7');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (13, 16, '2016-4-16', '2016-2-19', '2017-3-10', 'PRORRDESCR8', 'PRORRDETALLE8');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (2, 2, '833-2-5', '754-6-23', '2017-10-29', 'PRORRDESCR9', 'PRORRDETALLE9');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (0, 7, '2016-6-14', '2016-2-27', '2017-4-28', 'PRORRDESCR10', 'PRORRDETALLE10');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (11, 0, '1639-5-8', '2016-10-17', '2017-12-1', 'PRORRDESCR11', 'PRORRDETALLE11');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (18, 0, '1371-7-17', '494-10-31', '2017-11-22', 'PRORRDESCR12', 'PRORRDETALLE12');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (7, 5, '1265-9-2', '1408-10-15', '1983-2-1', 'PRORRDESCR13', 'PRORRDETALLE13');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (19, 12, '638-4-2', '1188-3-18', '1679-9-2', 'PRORRDESCR14', 'PRORRDETALLE14');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (8, 8, '952-10-14', '1241-9-30', '1485-6-26', 'PRORRDESCR15', 'PRORRDETALLE15');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (12, 7, '885-6-21', '2016-12-21', '2017-9-6', 'PRORRDESCR16', 'PRORRDETALLE16');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (4, 10, '1714-1-22', '2016-3-16', '2017-8-21', 'PRORRDESCR17', 'PRORRDETALLE17');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (15, 7, '421-6-14', '1137-9-17', '2017-12-30', 'PRORRDESCR18', 'PRORRDETALLE18');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (6, 19, '1515-7-13', '1758-8-25', '1912-6-8', 'PRORRDESCR19', 'PRORRDETALLE19');

insert into PRORROGA (PRO_CODIGO, DIS_CODIGO, PRO_FECHAINT, PRO_FECHAINICIO, PRO_FECHAFIN, PRO_DESCRIPCION, PRO_DETALLE) values (5, 2, '504-11-15', '1-1-1', '266-2-11', 'PRORRDESCR20', 'PRORRDETALLE20');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (2, 3, '2017-11-22', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (18, 2, '2017-6-26', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (10, 7, '2017-4-28', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (1, 4, '2017-11-15', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (13, 5, '1106-6-22', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (3, 10, '2017-2-13', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (15, 5, '2017-1-31', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (9, 17, '981-4-22', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (7, 7, '903-8-21', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (11, 6, '353-8-24', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (16, 6, '1742-1-2', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (8, 3, '2017-5-12', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (17, 0, '1560-12-4', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (6, 17, '1473-3-10', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (19, 10, '2017-1-1', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (14, 10, '2017-3-24', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (12, 1, '2017-11-20', 'RP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (5, 16, '1401-9-25', 'AP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (4, 3, '2017-1-31', 'EP');

insert into EXAMEN_COMPLEXIVO (EXA_CODIGO, PER_CODIGO, EXA_FECHAINICIO, EXA_ESTADO) values (0, 13, '770-8-27', 'RP');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (13, 12, '2017-5-11');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (1, 6, '2017-5-6');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (14, 1, '912-3-1');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (10, 12, '2017-11-24');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (3, 2, '2017-1-8');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (6, 13, '2017-8-20');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (15, 15, '2017-1-1');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (5, 11, '1158-3-22');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (12, 3, '2017-1-31');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (17, 4, '1475-11-7');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (7, 1, '2017-6-27');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (8, 8, '482-5-30');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (2, 18, '1030-4-6');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (16, 5, '278-4-26');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (19, 13, '540-1-9');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (4, 12, '1830-4-25');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (9, 8, '829-3-10');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (0, 1, '366-5-4');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (18, 19, '162-10-7');

insert into INTENTOS (INT_CODIGO, EXA_CODIGO, INT_FECHAINT) values (11, 12, '680-12-8');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (15, 4, 6, '2016-10-10', 'REVISIONDESCR1');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (10, 1, 16, '2016-1-1', 'REVISIONDESCR2');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (6, 10, 12, '2016-4-6', 'REVISIONDESCR3');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (14, 14, 15, '1058-5-6', 'REVISIONDESCR4');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (3, 16, 17, '1551-8-4', 'REVISIONDESCR5');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (8, 12, 10, '2016-12-3', 'REVISIONDESCR6');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (9, 5, 9, '2016-6-7', 'REVISIONDESCR7');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (5, 16, 18, '2016-11-2', 'REVISIONDESCR8');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (0, 17, 18, '2016-3-9', 'REVISIONDESCR9');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (7, 18, 8, '1253-6-19', 'REVISIONDESCR10');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (13, 1, 12, '1720-8-5', 'REVISIONDESCR11');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (16, 6, 15, '1427-2-3', 'REVISIONDESCR12');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (17, 18, 10, '1199-1-9', 'REVISIONDESCR13');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (11, 15, 11, '1865-5-12', 'REVISIONDESCR14');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (2, 17, 12, '1345-10-30', 'REVISIONDESCR15');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (18, 12, 19, '1988-4-24', 'REVISIONDESCR16');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (19, 4, 18, '2016-5-27', 'REVISIONDESCR17');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (12, 7, 8, '2016-4-25', 'REVISIONDESCR18');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (1, 14, 1, '1642-11-21', 'REVISIONDESCR19');

insert into REVISIONES (OBS_CODIGO, DIS_CODIGO, RED_CODIGO, OBS_FECHA, OBS_DESCRIPCION) values (4, 18, 16, '413-3-11', 'REVISIONDESCR20');

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (19, 4);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (6, 17);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (17, 19);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (2, 10);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (12, 16);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (7, 2);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (8, 7);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (1, 11);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (13, 3);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (18, 15);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (0, 0);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (9, 5);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (10, 8);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (5, 6);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (16, 14);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (3, 18);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (11, 1);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (15, 13);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (14, 12);

insert into REVDIR_X_DISERTACION (RED_CODIGO, DIS_CODIGO) values (4, 9);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (9, 2);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (5, 18);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (17, 10);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (8, 1);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (6, 13);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (10, 3);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (18, 15);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (2, 9);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (11, 7);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (15, 11);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (3, 16);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (1, 8);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (19, 17);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (13, 6);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (7, 19);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (16, 14);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (4, 12);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (12, 5);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (14, 4);

insert into MATSORTEADAS_X_EXAMEN (MAT_CODIGO, EXA_CODIGO) values (0, 0);

