<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Calendario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get calendario by calcodigo
     */
    function get_calendario($calcodigo)
    {
        return $this->db->get_where('calendarios',array('calcodigo'=>$calcodigo))->row_array();
    }
    
    /*
     * Get all calendarios
     */
    function get_all_calendarios()
    {
        return $this->db->get('calendarios')->result_array();
    }
    
    /*
     * function to add new calendario
     */
    function add_calendario($params)
    {
        $this->db->insert('calendarios',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update calendario
     */
    function update_calendario($calcodigo,$params)
    {
        $this->db->where('calcodigo',$calcodigo);
        $response = $this->db->update('calendarios',$params);
        if($response)
        {
            return "calendario updated successfully";
        }
        else
        {
            return "Error occuring while updating calendario";
        }
    }
    
    /*
     * function to delete calendario
     */
    function delete_calendario($calcodigo)
    {
        $response = $this->db->delete('calendarios',array('calcodigo'=>$calcodigo));
        if($response)
        {
            return "calendario deleted successfully";
        }
        else
        {
            return "Error occuring while deleting calendario";
        }
    }
}
