<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Carrera_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carrera by carr_codigo
     */
    function get_carrera($carr_codigo)
    {
        return $this->db->get_where('carreras',array('carr_codigo'=>$carr_codigo))->row_array();
    }
    
    /*
     * Get all carreras
     */
    function get_all_carreras($limit = 5)
    {
        $offset = $this->uri->segment(3);
        return $this->db->limit($limit, $offset)
            ->get('carreras')->result_array();
    }
    /*Get total number of rows (used in pagination)*/
    private $table = "carreras";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }
    /*
     * function to add new carrera
     */
    function add_carrera($params)
    {
        $this->db->insert('carreras',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update carrera
     */
    function update_carrera($carr_codigo,$params)
    {
        $this->db->where('carr_codigo',$carr_codigo);
        $response = $this->db->update('carreras',$params);
        if($response)
        {
            return "carrera updated successfully";
        }
        else
        {
            return "Error occuring while updating carrera";
        }
    }
    
    /*
     * function to delete carrera
     */
    function delete_carrera($carr_codigo)
    {
        $response = $this->db->delete('carreras',array('carr_codigo'=>$carr_codigo));
        if($response)
        {
            return "carrera deleted successfully";
        }
        else
        {
            return "Error occuring while deleting carrera";
        }
    }
}
