<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Carrera_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carrera by CARR_CODIGO
     */
    function get_carrera($CARR_CODIGO)
    {
        return $this->db->get_where('CARRERAS',array('CARR_CODIGO'=>$CARR_CODIGO))->row_array();
    }
    
    /*
     * Get all carreras
     */
    function get_all_carreras()
    {
        return $this->db->get('CARRERAS')->result_array();
    }
    
    /*
     * function to add new carrera
     */
    function add_carrera($params)
    {
        $this->db->insert('CARRERAS',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carrera
     */
    function update_carrera($CARR_CODIGO,$params)
    {
        $this->db->where('CARR_CODIGO',$CARR_CODIGO);
        $response = $this->db->update('CARRERAS',$params);
        if($response)
        {
            return "carrera updated successfully";
        }
        else
        {
            return "Error occuring while updating carrera";
        }
    }
    
    /*
     * function to delete carrera
     */
    function delete_carrera($CARR_CODIGO)
    {
        $response = $this->db->delete('CARRERAS',array('CARR_CODIGO'=>$CARR_CODIGO));
        if($response)
        {
            return "carrera deleted successfully";
        }
        else
        {
            return "Error occuring while deleting carrera";
        }
    }
}
