<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Escuela_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get escuela by esc_codigo
     */
    function get_escuela($esc_codigo)
    {
        return $this->db->get_where('escuelas',array('esc_codigo'=>$esc_codigo))->row_array();
    }

    function getEscuelaBusqueda($param, $limit = 5) {

        // $offset = $this->uri->segment(3);
        // $this->db->limit($limit, $offset);

        $this->db->select('*','facu_descripcion');
        $this->db->from('escuelas','facultades');
        $this->db->join('facultades','facultades.facu_codigo=escuelas.facu_codigo');
        $this->db->like('esc_descripcion', $param, 'both');
        $this->db->or_like('facu_descripcion', $param, 'both');

        $query=$this->db->get();
        return $query->result_array();

    }

    function countParamSearch($param)
    {
        $this->db->select('*','facu_descripcion');
        $this->db->from('escuelas','facultades');
        $this->db->join('facultades','facultades.facu_codigo=escuelas.facu_codigo');
        $this->db->like('esc_descripcion', $param, 'both');
        $this->db->or_like('facu_descripcion', $param, 'both');

        $query=$this->db->get();

        return $query->num_rows();
    }
    private $table = "escuelas";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }


    /*
     * Get all escuelas
     */

    function get_all_escuelas_()
    {
        return $this->db->get('escuelas')->result_array();
    }

    function get_all_escuelas($limit = 5)
    {
        $offset = $this->uri->segment(3);
        //return $this->db->limit($limit, $offset)
        //    ->get('escuelas')->result_array();
        $this->db->limit($limit, $offset);
        $this->db->select('*','facu_descripcion');
        $this->db->from('escuelas','facultades');
        $this->db->join('facultades','facultades.facu_codigo=escuelas.facu_codigo');
        $this->db->order_by('esc_codigo','asc');
        $query=$this->db->get();
        return $query->result_array();
    }
    
    /*
     * function to add new escuela
     */
    function add_escuela($params)
    {
        $this->db->insert('escuelas',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update escuela
     */
    function update_escuela($esc_codigo,$params)
    {
        $this->db->where('esc_codigo',$esc_codigo);
        $response = $this->db->update('escuelas',$params);
        if($response)
        {
            return "escuela updated successfully";
        }
        else
        {
            return "Error occuring while updating escuela";
        }
    }
    
    /*
     * function to delete escuela
     */
    function delete_escuela($esc_codigo)
    {
        $response = $this->db->delete('escuelas',array('esc_codigo'=>$esc_codigo));
        if($response)
        {
            return "escuela deleted successfully";
        }
        else
        {
            return "Error occuring while deleting escuela";
        }
    }
}
