<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Escuelas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get escuelas by esc_codigo
     */
    function get_escuelas($esc_codigo)
    {
        return $this->db->get_where('escuelas',array('esc_codigo'=>$esc_codigo))->row_array();
    }
    
    /*
     * Get all escuelas
     */
    function get_all_escuelas()
    {
        return $this->db->get('escuelas')->result_array();
    }
    
    /*
     * function to add new escuelas
     */
    function add_escuelas($params)
    {
        $this->db->insert('escuelas',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update escuelas
     */
    function update_escuelas($esc_codigo,$params)
    {
        $this->db->where('esc_codigo',$esc_codigo);
        $response = $this->db->update('escuelas',$params);
        if($response)
        {
            return "escuelas updated successfully";
        }
        else
        {
            return "Error occuring while updating escuelas";
        }
    }
    
    /*
     * function to delete escuelas
     */
    function delete_escuelas($esc_codigo)
    {
        $response = $this->db->delete('escuelas',array('esc_codigo'=>$esc_codigo));
        if($response)
        {
            return "escuelas deleted successfully";
        }
        else
        {
            return "Error occuring while deleting escuelas";
        }
    }
}
