<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by PER_CODIGO
     */
    function get_estudiante($PER_CODIGO)
    {
        return $this->db->get_where('estudiante',array('per_codigo'=>$PER_CODIGO))->row_array();
    }
    
    /*
     * Get all estudiante
     */
    function get_all_estudiante()
    {
        return $this->db->get('estudiante')->result_array();
    }
    
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($PER_CODIGO,$params)
    {
        $this->db->where('per_codigo',$PER_CODIGO);
        $response = $this->db->update('estudiante',$params);
        if($response)
        {
            return "estudiante updated successfully";
        }
        else
        {
            return "Error occuring while updating estudiante";
        }
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($PER_CODIGO)
    {
        $response = $this->db->delete('estudiante',array('per_codigo'=>$PER_CODIGO));
        if($response)
        {
            return "estudiante deleted successfully";
        }
        else
        {
            return "Error occuring while deleting estudiante";
        }
    }
}
