<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Examen_complexivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get examen_complexivo by exa_codigo
     */
    function get_examen_complexivo($exa_codigo)
    {
        return $this->db->get_where('examen_complexivo',array('exa_codigo'=>$exa_codigo))->row_array();
    }
    private $table = "examen_complexivo";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }
    /*
     * Get all examenes_complexivo
     */
    function get_all_examenes_complexivo($limit = 5)
    {
        $offset = $this->uri->segment(3);
        return $this->db->limit($limit, $offset)
            ->get('examen_complexivo')->result_array();
    }
    
    /*
     * function to add new examen_complexivo
     */
    function add_examen_complexivo($params)
    {
        $this->db->insert('examen_complexivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update examen_complexivo
     */
    function update_examen_complexivo($exa_codigo,$params)
    {
        $this->db->where('exa_codigo',$exa_codigo);
        $response = $this->db->update('examen_complexivo',$params);
        if($response)
        {
            return "examen_complexivo updated successfully";
        }
        else
        {
            return "Error occuring while updating examen_complexivo";
        }
    }
    
    /*
     * function to delete examen_complexivo
     */
    function delete_examen_complexivo($exa_codigo)
    {
        $response = $this->db->delete('examen_complexivo',array('exa_codigo'=>$exa_codigo));
        if($response)
        {
            return "examen_complexivo deleted successfully";
        }
        else
        {
            return "Error occuring while deleting examen_complexivo";
        }
    }
}
