<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Facultades_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get facultades by facu_codigo
     */
    function get_facultades($facu_codigo)
    {
        return $this->db->get_where('facultades',array('facu_codigo'=>$facu_codigo))->row_array();
    }
    private $table = "facultades";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }
    function getFacultadBusqueda($param, $limit = 5) {

        // $offset = $this->uri->segment(3);
        // $this->db->limit($limit, $offset);

        $this->db->select('*');
        $this->db->from('facultades');
        $this->db->like('facu_descripcion', $param, 'both');
        $query=$this->db->get();
        return $query->result_array();

    }

    function countParamSearch($param)
    {
        $this->db->select('*');
        $this->db->from('facultades');

        $this->db->like('facu_descripcion', $param, 'both');
        $query=$this->db->get();


        return $query->num_rows();
    }
    /*
     * Get all facultades
     */
    function get_all_facultades_()
    {
        return $this->db->get('facultades')->result_array();
    }

    function get_all_facultades($limit = 5)
    {
        $offset = $this->uri->segment(3);
        return $this->db->limit($limit, $offset)
            ->get('facultades')->result_array();
    }
    
    /*
     * function to add new facultades
     */
    function add_facultades($params)
    {
        $this->db->insert('facultades',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update facultades
     */
    function update_facultades($facu_codigo,$params)
    {
        $this->db->where('facu_codigo',$facu_codigo);
        $response = $this->db->update('facultades',$params);
        if($response)
        {
            return "facultades updated successfully";
        }
        else
        {
            return "Error occuring while updating facultades";
        }
    }
    
    /*
     * function to delete facultades
     */
    function delete_facultades($facu_codigo)
    {
        $response = $this->db->delete('facultades',array('facu_codigo'=>$facu_codigo));
        if($response)
        {
            return "facultades deleted successfully";
        }
        else
        {
            return "Error occuring while deleting facultades";
        }
    }
}
