<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Intento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get intento by int_codigo
     */
    function get_intento($int_codigo)
    {
        return $this->db->get_where('intentos',array('int_codigo'=>$int_codigo))->row_array();
    }
    
    /*
     * Get all intentos
     */
    function get_all_intentos()
    {
        return $this->db->get('intentos')->result_array();
    }
    
    /*
     * function to add new intento
     */
    function add_intento($params)
    {
        $this->db->insert('intentos',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update intento
     */
    function update_intento($int_codigo,$params)
    {
        $this->db->where('int_codigo',$int_codigo);
        $response = $this->db->update('intentos',$params);
        if($response)
        {
            return "intento updated successfully";
        }
        else
        {
            return "Error occuring while updating intento";
        }
    }
    
    /*
     * function to delete intento
     */
    function delete_intento($int_codigo)
    {
        $response = $this->db->delete('intentos',array('int_codigo'=>$int_codigo));
        if($response)
        {
            return "intento deleted successfully";
        }
        else
        {
            return "Error occuring while deleting intento";
        }
    }
}
