<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Logged_action_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get logged_action by action_tstamp
     */
    function get_logged_action($action_tstamp)
    {

        $a=explode( '%20', $action_tstamp ) ;

        $action_tstamp=$a[0].' '.$a[1];
        $logged_action = $this->db->query("
            SELECT
                *

            FROM
                logged_actions

            WHERE
                action_tstamp = ?
        ",array($action_tstamp))->row_array();

        return $logged_action;
    }
    
    /*
     * Get all logged_actions
     */
    function get_all_logged_actions()
    {
        $logged_actions = $this->db->query("
            SELECT
                *

            FROM
                logged_actions

        ")->result_array();

        return $logged_actions;
    }
    
    /*
     * function to add new logged_action
     */
    function add_logged_action($params)
    {
        $this->db->insert('logged_actions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update logged_action
     */
    function update_logged_action($action_tstamp,$params)
    {
        $this->db->where('action_tstamp',$action_tstamp);
        $response = $this->db->detail('logged_actions',$params);
        if($response)
        {
            return "logged_action updated successfully";
        }
        else
        {
            return "Error occuring while updating logged_action";
        }
    }
    
    /*
     * function to delete logged_action
     */
    function delete_logged_action($action_tstamp)
    {
        $response = $this->db->delete('logged_actions',array('action_tstamp'=>$action_tstamp));
        if($response)
        {
            return "logged_action deleted successfully";
        }
        else
        {
            return "Error occuring while deleting logged_action";
        }
    }
}
