<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Materia_x_plan_de_estudio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get materia_x_plan_de_estudio by plan_codigo
     */
    function get_materia_x_plan_de_estudio()
    {
        $plan_codigo=$this->uri->segment(3);
        $mat_codigo=$this->uri->segment(4);
        $pac_codigo=$this->uri->segment(5);
        return $this->db->get_where('materia_x_plan_de_estudio',array('plan_codigo'=>$plan_codigo,'mat_codigo'=>$mat_codigo,'pac_codigo'=>$pac_codigo))->row_array();
    }
    
    /*
     * Get all materia_x_plan_de_estudio
     */
    function get_all_materia_x_plan_de_estudio()
    {
        return $this->db->get('materia_x_plan_de_estudio')->result_array();
    }
    
    /*
     * function to add new materia_x_plan_de_estudio
     */
    function add_materia_x_plan_de_estudio($params)
    {
        $this->db->insert('materia_x_plan_de_estudio',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update materia_x_plan_de_estudio
     */
    function update_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo,$params)
    {
        $this->db->where(array('plan_codigo'=>$plan_codigo,'mat_codigo'=>$mat_codigo,'pac_codigo'=>$pac_codigo));
        $response = $this->db->update('materia_x_plan_de_estudio',$params);
        if($response)
        {
            return "materia_x_plan_de_estudio updated successfully";
        }
        else
        {
            return "Error occuring while updating materia_x_plan_de_estudio";
        }
    }
    
    /*
     * function to delete materia_x_plan_de_estudio
     */
    function delete_materia_x_plan_de_estudio($plan_codigo,$mat_codigo,$pac_codigo)
    {
        $response = $this->db->delete('materia_x_plan_de_estudio',array('plan_codigo'=>$plan_codigo,'mat_codigo'=>$mat_codigo,'pac_codigo'=>$pac_codigo));
        if($response)
        {
            return "materia_x_plan_de_estudio deleted successfully";
        }
        else
        {
            return "Error occuring while deleting materia_x_plan_de_estudio";
        }
    }
}
