<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Modulo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modulo by mod_codigo
     */
    function get_modulo($mod_codigo)
    {
        return $this->db->get_where('modulo',array('mod_codigo'=>$mod_codigo))->row_array();
    }
    
    /*
     * Get all modulos
     */
    function get_all_modulos()
    {
        return $this->db->get('modulo')->result_array();
    }
    
    /*
     * function to add new modulo
     */
    function add_modulo($params)
    {
        $this->db->insert('modulo',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update modulo
     */
    function update_modulo($mod_codigo,$params)
    {
        $this->db->where('mod_codigo',$mod_codigo);
        $response = $this->db->update('modulo',$params);
        if($response)
        {
            return "modulo updated successfully";
        }
        else
        {
            return "Error occuring while updating modulo";
        }
    }
    
    /*
     * function to delete modulo
     */
    function delete_modulo($mod_codigo)
    {
        $response = $this->db->delete('modulo',array('mod_codigo'=>$mod_codigo));
        if($response)
        {
            return "modulo deleted successfully";
        }
        else
        {
            return "Error occuring while deleting modulo";
        }
    }
}
