<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Periodos_academicos2_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periodos_academicos2 by pac_codigo
     */
    function get_periodos_academicos2($pac_codigo)
    {
        return $this->db->get_where('periodos_academicos2',array('pac_codigo'=>$pac_codigo))->row_array();
    }
    
    /*
     * Get all periodos_academicos2
     */
    function get_all_periodos_academicos2()
    {
        return $this->db->get('periodos_academicos2')->result_array();
    }
    
    /*
     * function to add new periodos_academicos2
     */
    function add_periodos_academicos2($params)
    {
        $this->db->insert('periodos_academicos2',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update periodos_academicos2
     */
    function update_periodos_academicos2($pac_codigo,$params)
    {
        $this->db->where('pac_codigo',$pac_codigo);
        $response = $this->db->update('periodos_academicos2',$params);
        if($response)
        {
            return "periodos_academicos2 updated successfully";
        }
        else
        {
            return "Error occuring while updating periodos_academicos2";
        }
    }
    
    /*
     * function to delete periodos_academicos2
     */
    function delete_periodos_academicos2($pac_codigo)
    {
        $response = $this->db->delete('periodos_academicos2',array('pac_codigo'=>$pac_codigo));
        if($response)
        {
            return "periodos_academicos2 deleted successfully";
        }
        else
        {
            return "Error occuring while deleting periodos_academicos2";
        }
    }
}
