<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Periodos_academicos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periodo_academico by pac_codigo
     */
    function get_periodo_academico($pac_codigo)
    {
        return $this->db->get_where('periodos_academicos2',array('pac_codigo'=>$pac_codigo))->row_array();
    }
    
    /*
     * Get all periodos_academicos
     */
    function get_all_periodos_academicos()
    {
        return $this->db->get('periodos_academicos2')->result_array();
    }
    
    /*
     * function to add new periodo_academico
     */
    function add_periodo_academico($params)
    {
        $this->db->insert('periodos_academicos2',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update periodo_academico
     */
    function update_periodo_academico($pac_codigo,$params)
    {
        $this->db->where('pac_codigo',$pac_codigo);
        $response = $this->db->update('periodos_academicos2',$params);
        if($response)
        {
            return "periodo_academico updated successfully";
        }
        else
        {
            return "Error occuring while updating periodo_academico";
        }
    }
    
    /*
     * function to delete periodo_academico
     */
    function delete_periodo_academico($pac_codigo)
    {
        $response = $this->db->delete('periodos_academicos2',array('pac_codigo'=>$pac_codigo));
        if($response)
        {
            return "periodo_academico deleted successfully";
        }
        else
        {
            return "Error occuring while deleting periodo_academico";
        }
    }
}
