<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Periodos_academicos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periodos_academicos by pac_codigo
     */
    function get_periodos_academicos($pac_codigo)
    {
        return $this->db->get_where('periodos_academicos',array('pac_codigo'=>$pac_codigo))->row_array();
    }
    
    /*
     * Get all periodos_academicos
     */
    function get_all_periodos_academicos()
    {
        return $this->db->get('periodos_academicos')->result_array();
    }
    
    /*
     * function to add new periodos_academicos
     */
    function add_periodos_academicos($params)
    {
        $this->db->insert('periodos_academicos',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update periodos_academicos
     */
    function update_periodos_academicos($pac_codigo,$params)
    {
        $this->db->where('pac_codigo',$pac_codigo);
        $response = $this->db->update('periodos_academicos',$params);
        if($response)
        {
            return "periodos_academicos updated successfully";
        }
        else
        {
            return "Error occuring while updating periodos_academicos";
        }
    }
    
    /*
     * function to delete periodos_academicos
     */
    function delete_periodos_academicos($pac_codigo)
    {
        $response = $this->db->delete('periodos_academicos',array('pac_codigo'=>$pac_codigo));
        if($response)
        {
            return "periodos_academicos deleted successfully";
        }
        else
        {
            return "Error occuring while deleting periodos_academicos";
        }
    }
}
