<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Permxrol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get permxrol by perm_codigo
     */
    function get_permxrol($perm_codigo)
    {
        return $this->db->get_where('permxrol',array('perm_codigo'=>$perm_codigo))->row_array();
    }
    private $table = "permxrol";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }

    /*
     * Get all permxrol
     */
    function get_all_permxrol($limit = 5)
    {
        $offset = $this->uri->segment(3);
        return $this->db->limit($limit, $offset)
            ->get('permxrol')->result_array();
    }
    /*
     * Get permisos asociados a un rol
     */
    function get_perm_x_rol($rol_codigo)
    {
        return $this->db->get_where('permxrol',array('rol_codigo'=>$rol_codigo))->result_array();
    }
    /*
     * function to add new permxrol
     */

    function add_permxrol($params)
    {
        $this->db->insert('permxrol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update permxrol
     */
    function update_permxrol($perm_codigo,$params)
    {
        $this->db->where('perm_codigo',$perm_codigo);
        $response = $this->db->update('permxrol',$params);
        if($response)
        {
            return "permxrol updated successfully";
        }
        else
        {
            return "Error occuring while updating permxrol";
        }
    }
    
    /*
     * function to delete permxrol
     */
    function delete_permxrol($perm_codigo)
    {
        $response = $this->db->delete('permxrol',array('perm_codigo'=>$perm_codigo));
        if($response)
        {
            return "permxrol deleted successfully";
        }
        else
        {
            return "Error occuring while deleting permxrol";
        }
    }
}
