<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Permxrol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get permxrol by zpermcodigo
     */
    function get_permxrol($zpermcodigo)
    {
        return $this->db->get_where('permxrol',array('zpermcodigo'=>$zpermcodigo))->row_array();
    }
    
    /*
     * Get all permxrol
     */
    function get_all_permxrol()
    {
        return $this->db->get('permxrol')->result_array();
    }

    /*
     * Get permisos asociados a un rol
     */
    function get_perm_x_rol($zrolcodigo)
    {
        return $this->db->get_where('permxrol',array('zrolcodigo'=>$zrolcodigo))->result_array();
    }
    
    /*
     * function to add new permxrol
     */
    function add_permxrol($params)
    {
        $this->db->insert('permxrol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update permxrol
     */
    function update_permxrol($zpermcodigo,$params)
    {
        $this->db->where('zpermcodigo',$zpermcodigo);
        $response = $this->db->update('permxrol',$params);
        if($response)
        {
            return "permxrol updated successfully";
        }
        else
        {
            return "Error occuring while updating permxrol";
        }
    }
    
    /*
     * function to delete permxrol
     */
    function delete_permxrol($zpermcodigo)
    {
        $response = $this->db->delete('permxrol',array('zpermcodigo'=>$zpermcodigo));
        if($response)
        {
            return "permxrol deleted successfully";
        }
        else
        {
            return "Error occuring while deleting permxrol";
        }
    }
}
