<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Plan_de_estudio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plan_de_estudio by plan_codigo
     */
    function get_plan_de_estudio($plan_codigo)
    {
        return $this->db->get_where('plan_de_estudio',array('plan_codigo'=>$plan_codigo))->row_array();
    }
    private $table = "plan_de_estudio";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }
    function getPlanEstudioBusqueda($param, $limit = 5) {

        // $offset = $this->uri->segment(3);
        // $this->db->limit($limit, $offset);

        $this->db->select('*','carr_descripcion');
        $this->db->from('plan_de_estudio','carreras');
        $this->db->join('carreras','carreras.carr_codigo=plan_de_estudio.carr_codigo');
        $this->db->like('carr_descripcion', $param, 'both');
        $this->db->or_like('plan_descripcion', $param, 'both');


        $query=$this->db->get();
        return $query->result_array();

    }

    function countParamSearch($param)
    {
        $this->db->select('*','carr_descripcion');
        $this->db->from('plan_de_estudio','carreras');
        $this->db->join('carreras','carreras.carr_codigo=plan_de_estudio.carr_codigo');
        $this->db->like('carr_descripcion', $param, 'both');
        $this->db->or_like('plan_descripcion', $param, 'both');


        $query=$this->db->get();

        return $query->num_rows();
    }
    /*
     * Get all planes_de_estudio
     */
    function get_all_planes_de_estudio_()
    {
        return $this->db->get('plan_de_estudio')->result_array();
    }

    function get_all_planes_de_estudio($limit = 5)
    {
        $offset = $this->uri->segment(3);
        //return $this->db->limit($limit, $offset)
        //    ->get('plan_de_estudio')->result_array();
        $this->db->limit($limit, $offset);
        $this->db->select('*','carr_descripcion');
        $this->db->from('plan_de_estudio','carreras');
        $this->db->join('carreras','carreras.carr_codigo=plan_de_estudio.carr_codigo');
        $this->db->order_by('plan_codigo','asc');
        $query=$this->db->get();
        return $query->result_array();
    }
    
    /*
     * function to add new plan_de_estudio
     */
    function add_plan_de_estudio($params)
    {
        $this->db->insert('plan_de_estudio',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update plan_de_estudio
     */
    function update_plan_de_estudio($plan_codigo,$params)
    {
        $this->db->where('plan_codigo',$plan_codigo);
        $response = $this->db->update('plan_de_estudio',$params);
        if($response)
        {
            return "plan_de_estudio updated successfully";
        }
        else
        {
            return "Error occuring while updating plan_de_estudio";
        }
    }
    
    /*
     * function to delete plan_de_estudio
     */
    function delete_plan_de_estudio($plan_codigo)
    {
        $response = $this->db->delete('plan_de_estudio',array('plan_codigo'=>$plan_codigo));
        if($response)
        {
            return "plan_de_estudio deleted successfully";
        }
        else
        {
            return "Error occuring while deleting plan_de_estudio";
        }
    }
}
