<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Responsables_titulacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get responsables_titulacion by res_codigo
     */
    function get_responsables_titulacion($res_codigo)
    {
        return $this->db->get_where('responsables_titulacion',array('res_codigo'=>$res_codigo))->row_array();
    }
    private $table = "responsables_titulacion";
    function count()
    {
        return $this->db->count_all_results($this->table);
    }

    /*
     * Get all responsables_titulacion
     */
    function get_all_responsables_titulacion($limit = 5)
    {
        $offset = $this->uri->segment(3);
        return $this->db->limit($limit, $offset)
            ->get('responsables_titulacion')->result_array();
    }
    
    /*
     * function to add new responsables_titulacion
     */
    function add_responsables_titulacion($params)
    {
        $this->db->insert('responsables_titulacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update responsables_titulacion
     */
    function update_responsables_titulacion($res_codigo,$params)
    {
        $this->db->where('res_codigo',$res_codigo);
        $response = $this->db->update('responsables_titulacion',$params);
        if($response)
        {
            return "responsables_titulacion updated successfully";
        }
        else
        {
            return "Error occuring while updating responsables_titulacion";
        }
    }
    
    /*
     * function to delete responsables_titulacion
     */
    function delete_responsables_titulacion($res_codigo)
    {
        $response = $this->db->delete('responsables_titulacion',array('res_codigo'=>$res_codigo));
        if($response)
        {
            return "responsables_titulacion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting responsables_titulacion";
        }
    }
}
