<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Rev_dir_trab_titulacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rev_dir_trab_titulacion by red_codigo
     */
    function get_rev_dir_trab_titulacion($red_codigo)
    {
        return $this->db->get_where('rev_dir_trab_titulacion',array('red_codigo'=>$red_codigo))->row_array();
    }
    
    /*
     * Get all rev_dir_trab_titulacion
     */
    function get_all_rev_dir_trab_titulacion()
    {
        return $this->db->get('rev_dir_trab_titulacion')->result_array();
    }
    
    /*
     * function to add new rev_dir_trab_titulacion
     */
    function add_rev_dir_trab_titulacion($params)
    {
        $this->db->insert('rev_dir_trab_titulacion',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update rev_dir_trab_titulacion
     */
    function update_rev_dir_trab_titulacion($red_codigo,$params)
    {
        $this->db->where('red_codigo',$red_codigo);
        $response = $this->db->update('rev_dir_trab_titulacion',$params);
        if($response)
        {
            return "rev_dir_trab_titulacion updated successfully";
        }
        else
        {
            return "Error occuring while updating rev_dir_trab_titulacion";
        }
    }
    
    /*
     * function to delete rev_dir_trab_titulacion
     */
    function delete_rev_dir_trab_titulacion($red_codigo)
    {
        $response = $this->db->delete('rev_dir_trab_titulacion',array('red_codigo'=>$red_codigo));
        if($response)
        {
            return "rev_dir_trab_titulacion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting rev_dir_trab_titulacion";
        }
    }
}
