<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Revdir_x_disertacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get revdir_x_disertacion by dis_codigo
     */
    function get_revdir_x_disertacion()
    {
        $dis_codigo=$this->uri->segment(3);
        $prof_codigo=$this->uri->segment(4);
        return $this->db->get_where('revdir_x_disertacion',array('dis_codigo'=>$dis_codigo,'prof_codigo'=>$prof_codigo))->row_array();
    }
    
    /*
     * Get all revdir_x_disertacion
     */
    function get_all_revdir_x_disertacion()
    {
        return $this->db->get('revdir_x_disertacion')->result_array();
    }


    
    /*
     * function to add new revdir_x_disertacion
     */
    function add_revdir_x_disertacion($params)
    {
        $this->db->insert('revdir_x_disertacion',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update revdir_x_disertacion
     */
    function update_revdir_x_disertacion($dis_codigo,$prof_codigo,$params)
    {
        $this->db->where(array('dis_codigo'=>$dis_codigo,'prof_codigo'=>$prof_codigo));
        $response = $this->db->update('revdir_x_disertacion',$params);
        if($response)
        {
            return "revdir_x_disertacion updated successfully";
        }
        else
        {
            return "Error occuring while updating revdir_x_disertacion";
        }
    }
    
    /*
     * function to delete revdir_x_disertacion
     */
    function delete_revdir_x_disertacion($dis_codigo,$prof_codigo)
    {
        $response = $this->db->delete('revdir_x_disertacion',array('dis_codigo'=>$dis_codigo,'prof_codigo'=>$prof_codigo));
        if($response)
        {
            return "revdir_x_disertacion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting revdir_x_disertacion";
        }
    }
}
