<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Revision_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get revision by obs_codigo
     */
    function get_revision($obs_codigo)
    {
        return $this->db->get_where('revisiones',array('obs_codigo'=>$obs_codigo))->row_array();
    }
    
    /*
     * Get all revisiones
     */
    function get_all_revisiones()
    {
        return $this->db->get('revisiones')->result_array();
    }
    
    /*
     * function to add new revision
     */
    function add_revision($params)
    {
        $this->db->insert('revisiones',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update revision
     */
    function update_revision($obs_codigo,$params)
    {
        $this->db->where('obs_codigo',$obs_codigo);
        $response = $this->db->update('revisiones',$params);
        if($response)
        {
            return "revision updated successfully";
        }
        else
        {
            return "Error occuring while updating revision";
        }
    }
    
    /*
     * function to delete revision
     */
    function delete_revision($obs_codigo)
    {
        $response = $this->db->delete('revisiones',array('obs_codigo'=>$obs_codigo));
        if($response)
        {
            return "revision deleted successfully";
        }
        else
        {
            return "Error occuring while deleting revision";
        }
    }
}
