<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Rol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rol by rol_codigo
     */
    function get_rol($rol_codigo)
    {
        return $this->db->get_where('roles',array('rol_codigo'=>$rol_codigo))->row_array();
    }
    
    /*
     * Get all roles
     */
    function get_all_roles()
    {
        return $this->db->get('roles')->result_array();
    }
    
    /*
     * function to add new rol
     */
    function add_rol($params)
    {
        $this->db->insert('roles',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update rol
     */
    function update_rol($rol_codigo,$params)
    {
        $this->db->where('rol_codigo',$rol_codigo);
        $response = $this->db->update('roles',$params);
        if($response)
        {
            return "rol updated successfully";
        }
        else
        {
            return "Error occuring while updating rol";
        }
    }
    
    /*
     * function to delete rol
     */
    function delete_rol($rol_codigo)
    {
        $response = $this->db->delete('roles',array('rol_codigo'=>$rol_codigo));
        if($response)
        {
            return "rol deleted successfully";
        }
        else
        {
            return "Error occuring while deleting rol";
        }
    }
}
