<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Trabajo_disertacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trabajo_disertacion by dis_codigo
     */
    function get_trabajo_disertacion($dis_codigo)
    {
        return $this->db->get_where('trabajo_disertacion',array('dis_codigo'=>$dis_codigo))->row_array();
    }
    
    /*
     * Get all trabajos_disertacion
     */
    function get_all_trabajos_disertacion()
    {
        return $this->db->get('trabajo_disertacion')->result_array();
    }
    
    /*
     * function to add new trabajo_disertacion
     */
    function add_trabajo_disertacion($params)
    {
        $this->db->insert('trabajo_disertacion',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update trabajo_disertacion
     */
    function update_trabajo_disertacion($dis_codigo,$params)
    {
        $this->db->where('dis_codigo',$dis_codigo);
        $response = $this->db->update('trabajo_disertacion',$params);
        if($response)
        {
            return "trabajo_disertacion updated successfully";
        }
        else
        {
            return "Error occuring while updating trabajo_disertacion";
        }
    }
    
    /*
     * function to delete trabajo_disertacion
     */
    function delete_trabajo_disertacion($dis_codigo)
    {
        $response = $this->db->delete('trabajo_disertacion',array('dis_codigo'=>$dis_codigo));
        if($response)
        {
            return "trabajo_disertacion deleted successfully";
        }
        else
        {
            return "Error occuring while deleting trabajo_disertacion";
        }
    }
}
