<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Zrole_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get zrole by zrolcodigo
     */
    function get_zrole($zrolcodigo)
    {
        return $this->db->get_where('zroles',array('zrolcodigo'=>$zrolcodigo))->row_array();
    }
    
    /*
     * Get all zroles
     */
    function get_all_zroles()
    {
        return $this->db->get('zroles')->result_array();
    }
    
    /*
     * function to add new zrole
     */
    function add_zrole($params)
    {
        $this->db->insert('zroles',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update zrole
     */
    function update_zrole($zrolcodigo,$params)
    {
        $this->db->where('zrolcodigo',$zrolcodigo);
        $response = $this->db->update('zroles',$params);
        if($response)
        {
            return "zrole updated successfully";
        }
        else
        {
            return "Error occuring while updating zrole";
        }
    }
    
    /*
     * function to delete zrole
     */
    function delete_zrole($zrolcodigo)
    {
        $response = $this->db->delete('zroles',array('zrolcodigo'=>$zrolcodigo));
        if($response)
        {
            return "zrole deleted successfully";
        }
        else
        {
            return "Error occuring while deleting zrole";
        }
    }
}
