<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Zusuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get zusuario by zusrcodigo
     */
    function get_zusuario($zusrcodigo)
    {
        return $this->db->get_where('zusuarios',array('zusrcodigo'=>$zusrcodigo))->row_array();
    }
    
    /*
     * Get all zusuarios
     */
    function get_all_zusuarios()
    {
        return $this->db->get('zusuarios')->result_array();
    }
    
    /*
     * function to add new zusuario
     */
    function add_zusuario($params)
    {
        $this->db->insert('zusuarios',$params);
        //return $this->db->insert_id();
    }
    
    /*
     * function to update zusuario
     */
    function update_zusuario($zusrcodigo,$params)
    {
        $this->db->where('zusrcodigo',$zusrcodigo);
        $response = $this->db->update('zusuarios',$params);
        if($response)
        {
            return "zusuario updated successfully";
        }
        else
        {
            return "Error occuring while updating zusuario";
        }
    }
    
    /*
     * function to delete zusuario
     */
    function delete_zusuario($zusrcodigo)
    {
        $response = $this->db->delete('zusuarios',array('zusrcodigo'=>$zusrcodigo));
        if($response)
        {
            return "zusuario deleted successfully";
        }
        else
        {
            return "Error occuring while deleting zusuario";
        }
    }
}
